-- ============================================================
-- MMPI PostgreSQL Data Import
-- Phase 1: All reference data
-- ============================================================
-- Run after: 01_schema.sql
-- Usage: psql -U mmpi_user -d mmpi_db -f 02_data.sql
-- ============================================================

BEGIN;

-- ============================================================
-- 0. QUESTION CATEGORIES
-- ============================================================
INSERT INTO question_category (name, id) VALUES
    ('Genel', 1),
    ('Aile', 2),
    ('Sağlık', 3),
    ('Cinsellik', 4),
    ('Duygusal', 5),
    ('Sosyal', 6)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 1. QUESTIONS (566 MMPI questions)
-- Source: dokumanlar/questions_insert.sql
-- ============================================================
INSERT INTO questions (question_number, question_text, category_id) VALUES
(1,'Teknik yazılardan hoşlanırım.', 1),
(2,'İştahım iyidir.', 1),
(3,'Çok defa sabahları dinç ve dinlenmiş olarak uyanırım.', 1),
(4,'Kütüphaneci olarak çalışmayı seveceğimi sanıyorum.', 1),
(5,'Gürültüden kolayca uyanırım.', 1),
(6,'Cinayet haberlerini okumaktan hoşlanırım.', 1),
(7,'Çoğu zaman el ve ayaklarımın sıcaklığı iyidir.', 1),
(8,'Günlük hayatım beni ilgilendirecek şeylerle doludur.', 1),
(9,'Bugün de hemen hemen eskisi kadar iyi çalışabiliyorum.', 1),
(10,'Çoğu zaman boğazım tıkanır gibi olur.', 1),
(11,'İnsan rüyalarını anlamaya çalışmalı ve kendini onlara göre ayarlamalıdır.', 1),
(12,'Polis romanlarından ya da esrarengiz yazılardan hoşlanırım.', 1),
(13,'Büyük bir sinir gerginliği içinde çalışırım.', 1),
(14,'Ayda bir iki defa ishal olurum.', 1),
(15,'Arasıra söylenemeyecek kadar ayıp şeyler düşünürüm.', 1),
(16,'Hayatta kötülükler hep beni bulur.', 1),
(17,'Babam iyi bir adamdır.', 2),
(18,'Pek seyrek kabız olurum.', 1),
(19,'Yeni bir işe girince kimin gözüne girmem gerektiğini öğrenmek isterim.', 1),
(20,'Cinsel yaşamımdan memnunum.', 4),
(21,'Zaman zaman evi bırakıp gitmek istemişimdir.', 1),
(22,'Arasıra kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.', 1),
(23,'Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.', 3),
(24,'Kimse beni anlamıyor.', 1),
(25,'Şarkıcı olmayı isterim.', 1),
(26,'Başım derde girince susmayı tercih ederim.', 1),
(27,'Bazen kötü ruhların beni etkileri altına aldığını hissederim.', 1),
(28,'Kötülüğe kötülükle karşılık vermek prensibimdir.', 1),
(29,'Çoğu kez midem ekşir.', 3),
(30,'Bazen canım küfretmek ister.', 1),
(31,'Sık sık geceleri kabus geçiririm.', 1),
(32,'Zihnimi bir iş üzerinde toplamada güçlük çekerim.', 1),
(33,'Başımdan çok garip ve tuhaf şeyler geçti.', 1),
(34,'Çoğu zaman öksürüğüm vardır.', 1),
(35,'Başkaları engel olmasaydı daha çok başarılı olurdum.', 1),
(36,'Sağlığım beni pek kaygılandırmaz.', 3),
(37,'Cinsel yaşamım yüzünden başım hiç derde girmedi.', 4),
(38,'Gençliğimde bir devre ufak tefek şeyler çaldım.', 1),
(39,'Bazen içimde bir şeyler kırmak isteği geçer.', 1),
(40,'Başka bir şey yapmaktansa çoğu zaman oturup hayal kurmayı severim.', 1),
(41,'Kendimi toparlayamadığım için günler; haftalar hatta aylarca hiç bir şeye el sürmediğim olur.', 1),
(42,'2m seçtiğim (veya seçmek istediğim) mesleği beğenmiyor.', 2),
(43,'Kuşkulu ve rahatsız uyurum.', 1),
(44,'Çoğu zaman başımın her tarafı ağrır.', 3),
(45,'Her zaman doğruyu söylemem.', 1),
(46,'Şimdi her zamankinden daha iyi düşünüp tartabiliyorum.', 1),
(47,'Ortada hiç bir neden yokken haftada bir ya da daha sık birdenbire her yanımı ateş basar.', 1),
(48,'Başkaları ile bir arada iken kulağıma çok garip şeyler gelmesinden rahatsız olurum.', 1),
(49,'Kanunların hemen hepsi kaldırılırsa daha iyi olur.', 1),
(50,'Bazen ruhum vücudumdan ayrılır.', 1),
(51,'Sağlığım birçok arkadaşımınki kadar iyidir.', 3),
(52,'Uzun zamandan beri görmediğim okul arkadaşlarım ya da tanıdıklarım önce benimle konuşmazlarsa onları görmemezlikten gelmeyi tercih ederim.', 6),
(53,'Hocaların dua okuyup üflemesi hastalığı iyileştirir.', 1),
(54,'Tanıdıklarımın çoğu beni sever.', 1),
(55,'Kalp ve göğüs ağrılarından hemen hemen hiç şikayetim yoktur.', 3),
(56,'Çocukken okuldan kaçtığım için bir iki defa cezalandırıldım.', 1),
(57,'İnsanlarla çabucak kaynaşırım.', 1),
(58,'Kur’an’ın buyurdukları bir bir çıkmaktadır.', 1),
(59,'Çok defa benden az bilenlerden emir alarak çalışmak zorunda kaldım.', 1),
(60,'Her gün gazetelerin baş yazılarını okumam.', 1),
(61,'Gerektiği gibi bir hayat yaşayamadım.', 1),
(62,'Vücudumun bazı yerlerinde çok defa yanma; gıdıklanma; karıncalanma veya uyuşukluk hissederim.', 1),
(63,'Büyük abdest yapmada ya da tutmada hiç bir güçlük çekmem.', 3),
(64,'Bazen başkalarının sabrını tüketecek kadar bir şeye saplanıp kalırım.', 1),
(65,'Babamı severim.', 2),
(66,'Etrafımda başkalarının görmedikleri eşya ve hayvanlar ya da insanlar görürüm.', 1),
(67,'Başkalarının mutlu göründüğü kadar mutlu olmayı isterdim.', 5),
(68,'Ensemde nadiren ağrı hissederim.', 3),
(69,'Kendi cinsimden olanları oldukça çekici bulurum.', 4),
(70,'Körebe oyunundan hoşlanırdım.', 1),
(71,'Birçok kimseler başkalarının ilgi ve yardımlarını sağlamak için talihsizliklerini abartırlar.', 1),
(72,'Hemen hemen her gün mide ağrılarından rahatsız olurum.', 3),
(73,'Ben önemli bir kimseyim.', 1),
(74,'Çoğu zaman kız olmayı isterdim. (Şayet kız iseniz) Kız olduğuma hiç üzülmedim.', 1),
(75,'Arasıra öfkelenirim.', 1),
(76,'Çoğu zaman kendimi hüzünlü hissederim.', 5),
(77,'Aşk romanları okumaktan hoşlanırım.', 1),
(78,'Şiiri severim.', 1),
(79,'Kolay incinmem.', 1),
(80,'Bazen hayvanlara rahat vermem.', 1),
(81,'Orman bekçiliği gibi işlerden hoşlanacağımı sanıyorum.', 1),
(82,'Tartışmalarda çabucak yenilirim.', 1),
(83,'Çok çalışabilen ya da çalışmak isteyen kişinin başarılı olma şansı yüksektir.', 1),
(84,'Bugünlerde artık hiç ilerleme umudum kalmamış gibi hissediyorum.', 5),
(85,'Kullanamayacak bile olsam bazen başkalarının ayakkabı; eldiven vb. gibi özel eşyaları o kadar hoşuma gider ki dokunmak ve aşırmak isterim.', 1),
(86,'Kendime hiç güvenim yoktur.', 5),
(87,'Çiçek satıcısı olmayı isterdim.', 1),
(88,'1 olarak hayatın yaşanmaya değer olduğu kanısındayım.', 1),
(89,'İnsanlara gerçeği kabul ettirmek güçtür.', 1),
(90,'Bugün yapmam gereken işleri ara sıra yarına bıraktığım olur.', 1),
(91,'Benimle alay edilmesine aldırmam.', 1),
(92,'Hemşire olmayı isterdim.', 1),
(93,'Yükselmek için birçok kimse yalan söylemekten çekinmez.', 1),
(94,'Sonradan pişman olacağım pek çok şeyi yaptığım olur.', 1),
(95,'Namazımı hemen hemen muntazaman kılarım.', 1),
(96,'2mle pek az kavga ederim.', 2),
(97,'Bazen zararlı ya da çok kötü işler yapmak için içimde çok güçlü bir istek duyarım.', 1),
(98,'Kıyamet gününe inanıyorum.', 1),
(99,'Gürültülü eğlencelere katılmaktan hoşlanırım.', 1),
(100,'Bildiğim bir konuda bir kimse saçma sapan ya da cahilce konuşursa onu hemen düzeltirim.', 1),
(101,'Bence cinsel yönden kadınlar da erkekler kadar serbest olmalıdır.', 4),
(102,'En büyük mücadelelerimi kendimle yaparım.', 1),
(103,'Vücudumda pek az seyirme ve kasılma olur.', 3),
(104,'Başıma ne gelirse gelsin aldırış etmiyorum.', 1),
(105,'Keyfim yerinde olmadığı zaman tersliğim üzerimdedir.', 1),
(106,'Çoğu zaman büyük bir hata ya da kötülük yaptığım duygusuna kapılırım.', 1),
(107,'Çoğu zaman mutluyumdur.', 5),
(108,'Çoğu zaman bana; kafam şişmiş ya da burnum tıkanmış gibi gelir.', 3),
(109,'Bazı kimseler o kadar amirane davranırlar ki haklı bile olsalar içimden dediklerinin aksini yapmak gelir.', 1),
(110,'Bana kötülük etmek isteyen biri var.', 1),
(111,'Sırf heyecanlanmak için tehlikeli bir işe girişmedim.', 1),
(112,'Doğru bildiğim şeyler için çoğu zaman direnmek zorunda kalırım.', 1),
(113,'Kanunların uygulanması gerektiğine inanırım.', 1),
(114,'Çoğu zaman başım sıkı bir çember içindeymiş gibi hissederim.', 3),
(115,'Ahirete inanırım.', 1),
(116,'Bahse girdiğim yarış ya da oyunlardan daha çok zevk alırım.', 1),
(117,'Birçok kimseler daha çok yakalanmaktan korktukları için dürüsttürler.', 1),
(118,'Dersten kaçtığım için ara sıra müdüre gönderildiğim oldu.', 1),
(119,'Konuşma tarzım her zamanki gibidir.', 1),
(120,'Evde sofra adabına dışarıdaki kadar dikkat etmem.', 1),
(121,'Aleyhimde bazı tertipler kurulduğuna inanıyorum.', 1),
(122,'Tanıdığım insanların çoğu kadar becerikli ve zeki olduğumu sanıyorum.', 1),
(123,'Beni takip edenler olduğuna inanıyorum.', 1),
(124,'Birçokları kaybetmektense çıkarlarını korumak için pek doğru olmayan yollara başvururlar.', 1),
(125,'Midemden oldukça rahatsızım.', 3),
(126,'Tiyatrodan hoşlanırım.', 1),
(127,'Dertlerimin çoğundan kimin sorumlu olduğunu biliyorum.', 1),
(128,'Kan görünce korkmam ya da fenalaşmam.', 5),
(129,'Bazen ters ve suratsız olurum.', 1),
(130,'Hiçbir zaman kan kusmadım ya da kan tükürmedim.', 3),
(131,'Hastalığa yakalanacağım diye kaygılanmam.', 3),
(132,'Çiçek koleksiyonu yapmayı ve evde çiçek yetiştirmeyi severim.', 1),
(133,'Hiçbir zaman normal olmayan cinsel ilişkilere girişmedim.', 4),
(134,'Bazen kafamdaki düşünceler o kadar hızlıdır ki söylemeyi yetiştiremem.', 1),
(135,'Farkedilmeyeceğimden emin olsam sinemaya biletsiz girerdim.', 1),
(136,'Bana iyilik yapan kimselerin genel olarak gizli bir amacı olabileceğini düşünürüm.', 1),
(137,'2 hayatımın tanıdığım kimselerin çoğununki kadar iyi olduğuna inanıyorum.', 2),
(138,'Eleştiri beni çok kırar.', 1),
(139,'Bazen sanki kendimi ya da başkasını incitmek zorundaymışım gibi hissederim.', 1),
(140,'Yemek pişirmeyi severim.', 1),
(141,'Davranışlarımı çoğu zaman etrafımdakilere göre ayarlarım.', 1),
(142,'Bazen hiçbir işe yaramadığımı düşünürüm.', 5),
(143,'Çocukken başlarına ne gelirse gelsin aralarındaki birliği koruyan bir gruptaydım.', 1),
(144,'Asker olmak isterim.', 1),
(145,'Bazen biriyle yumruk yumruğa kavgaya girişmek istediğim olur.', 1),
(146,'Seyahat edip gezip tozmadıkça mutlu olamam.', 1),
(147,'Çabuk karar vermediğim için çok fırsat kaçırdım.', 1),
(148,'Önemli bir iş üzerinde çalışırken başkalarının işimi yarıda kesmeleri sabrımı taşırır.', 1),
(149,'Hatıra defteri tutardım.', 1),
(150,'Oyunda kaybetmektense kazanmayı isterim.', 1),
(151,'Biri beni zehirlemeye çalışıyor.', 1),
(152,'Çoğu geceler zihnimi hiçbir şey kurcalamadan uykuya dalarım.', 1),
(153,'Son bir kaç yıl içinde sağlığım çoğu zaman iyi idi.', 3),
(154,'Hiç sinir nöbeti ya da havale geçirmedim.', 3),
(155,'Ne şişmanlıyorum ne de zayıflıyorum.', 1),
(156,'Bir şeyler yapıp sonra ne yaptığımı hatırlayamadığım zamanlar oldu.', 1),
(157,'Çoğu kez sebepsiz yere cezalandırıldım.', 1),
(158,'Çabuk ağlarım.', 1),
(159,'Okuduğumu eskisi kadar iyi anlayamıyorum.', 1),
(160,'Hayatımda hiçbir zaman kendimi şimdiki kadar iyi hissetmedim.', 5),
(161,'Bazen başımda bir sızı hissederim.', 3),
(162,'Birisinin bana kurnazca oyun etmesine çok içerlerim.', 1),
(163,'Çabucak yorulmam.', 1),
(164,'Üzerinde çalıştığım konularda okumayı ve incelemelerde bulunmayı severim.', 1),
(165,'Önemli kimseleri tanımayı severim; çünkü böylece kendimi de önemli bir kimse gibi görürüm.', 1),
(166,'Yüksek bir yerden aşağıya bakmaya korkarım.', 5),
(167,'2mden herhangi birinin mahkemelik olması beni rahatsız etmez.', 2),
(168,'Zihnimde bir gariplik var.', 1),
(169,'Parayı ellemekten korkmam.', 5),
(170,'Başkalarının hakkımda ne düşündükleri beni rahatsız etmez.', 1),
(171,'Bir eğlencede başkaları yapsalar bile; ben taşkınlık yapmaktan rahatsız olurum.', 6),
(172,'Çoğu kez utangaçlığımı örtbas etmek ihtiyacını duyarım.', 1),
(173,'Okulu severdim.', 1),
(174,'Hiç bayılma nöbeti geçirmedim.', 3),
(175,'Pek az başım döner ya da hiç dönmez.', 3),
(176,'Yılandan büyük bir korkum yoktur.', 5),
(177,'Annem iyi bir kadındır.', 2),
(178,'Hafızam genellikle iyidir.', 1),
(179,'Cinsel konularda sıkıntım vardır.', 4),
(180,'Yeni tanıştığım kimselerle konuşma konusu bulmada güçlük çekerim.', 6),
(181,'Canım sıkılınca heyecan yaratmayı severim.', 1),
(182,'Aklımı oynatmaktan korkuyorum.', 5),
(183,'Dilencilere para vermeyi doğru bulmam.', 1),
(184,'Sık sık nereden geldiğini bilmediğim sesler duyarım.', 1),
(185,'Herkes kadar iyi işitirim.', 3),
(186,'Bir şeyler yapmaya girişince ellerimin çok defa titrediğini fark ederim.', 3),
(187,'Ellerimde beceriksizlik ya da sakarlık yok.', 3),
(188,'Gözlerim yorulmadan uzun süre okuyabilirim.', 3),
(189,'Çoğu zaman bütün vücudumda bir halsizlik duyarım.', 3),
(190,'Başım pek az ağrır.', 3),
(191,'Bazen utanınca çok terlerim.', 3),
(192,'Yürürken dengemi hemen hemen hiç kaybetmem.', 3),
(193,'Saman nezlesi ya da astım nöbetlerim yoktur.', 3),
(194,'Hareketlerimi ve konuşmamı kontrol edemediğim fakat etrafımda olup bitenden haberdar olduğum nöbetler geçirdiğim oldu.', 1),
(195,'Tanıdığım herkesi sevmem.', 1),
(196,'Hiç görmediğim yerlere gitmekten hoşlanırım.', 1),
(197,'Biri beni soymaya (her şeyimi almaya) çalışıyor.', 1),
(198,'Çok az hayal kurarım.', 1),
(199,'Çocuklara cinsiyetle ilgili temel gerçekler öğretilmelidir.', 4),
(200,'Fikir ve düşüncelerimi çalmak isteyen biri var.', 1),
(201,'Keşke bu kadar utangaç olmasam.', 5),
(202,'Kendimi cezayı hak etmiş suçlu bir insan olarak görüyorum.', 1),
(203,'Gazeteci olmak isterdim.', 1),
(204,'Gazeteci olsaydım daha çok tiyatro haberleri yazmaktan hoşlanırdım.', 1),
(205,'Bazen çalmaktan ya da dükkanlardan eşya aşırmaktan kendimi alamam.', 1),
(206,'Birçok kimseden daha çok dindarımdır.', 1),
(207,'Çeşitli oyun ve eğlencelerden hoşlanırım.', 1),
(208,'Flört etmeyi severim.', 1),
(209,'Günahlarımın affedilmeyeceğine inanıyorum.', 1),
(210,'Her şeyin tadı aynı geliyor.', 3),
(211,'Gündüzleri uyuyabilirim fakat geceleri uyuyamam.', 3),
(212,'Evdekiler bana çocuk muamelesi yapıyor.', 2),
(213,'Yürürken kaldırımdaki yarıklara basmamaya dikkat ederim.', 1),
(214,'Cildimde üzülmeye değer kabarıklık ya da sivilce yok.', 3),
(215,'Çok içki kullandım.', 1),
(216,'Başka ailelere göre bizim evde sevgi ve arkadaşlık pek azdır.', 2),
(217,'Sık sık kendime bir şeyleri dert edinirim.', 5),
(218,'Hayvanların eziyet çektiğini görmek beni üzmez.', 1),
(219,'İnşaat müteahhitliğinden hoşlanacağımı sanıyorum.', 1),
(220,'Annemi çok severim.', 2),
(221,'Bilimden hoşlanırım.', 1),
(222,'Karşılığını veremeyeceğim durumlarda bile arkadaşlarımdan yardım istemekte güçlük çekmem.', 6),
(223,'Avlanmayı çok severim.', 1),
(224,'Annem babam hep beraber olduğum kimselerden çok defa hoşlanmıyorlar.', 2),
(225,'Bazen biraz dedikodu yaptığım olur.', 1),
(226,'2mdeki bazı kişilerde canımı çok sıkan alışkanlıklar var.', 2),
(227,'Uykuda gezdiğimi söylerler.', 1),
(228,'Bazen alışılmamış bir kolaylıkla karar verebileceğimi hissediyorum.', 1),
(229,'Çeşitli kulüp ve derneklere üye olmayı isterim.', 6),
(230,'Kalbimin hızlı çarptığını hemen hemen hiç hissetmem ve çok seyrek nefesim tıkanır.', 3),
(231,'Cinsiyet hakkında konuşmayı severim.', 4),
(232,'Bazen üzerime çok fazla iş alırım.', 1),
(233,'Pek çok insan karşı çıksa da kendi fikrimi sonuna kadar savunurum.', 6),
(234,'Çabuk kızar ve çabuk unuturum.', 1),
(235,'2 kurallarından oldukça bağımsız ve özgürüm.', 2),
(236,'Sıklıkla kara kara düşünürüm.', 5),
(237,'Akrabalarımın hemen hepsi bana karşı anlayış gösterir.', 2),
(238,'Zaman zaman yerimde duramayacak kadar huzursuzluk duyduğum devreler olur.', 5),
(239,'Aşkta hayal kırıklığına uğradım.', 4),
(240,'Görünüşüme hiç aldırmam.', 1),
(241,'Kendi içimde tutup başkalarına söylenemeyen şeyler hakkında sık sık rüya görürüm.', 1),
(242,'Birçoklarından daha sinirli sayılmam.', 1),
(243,'Hemen hemen hiçbir ağrı ve sızım yok.', 3),
(244,'Davranışlarım başkalarınca yanlış anlaşılmaya elverişlidir.', 1),
(245,'2m beni olduğumdan daha hatalı bulur.', 2),
(246,'Boynumda sık sık kırmızı lekeler olur.', 3),
(247,'Kimseden sevgi görmüyorum.', 1),
(248,'Bazen ortada hiçbir neden yokken hatta işler kötüye gittiği zaman bile kendimi fazlasıyla mutlu hissederim.', 5),
(249,'Öbür dünyada şeytan ve cehennem olduğuna inanırım.', 1),
(250,'Hayatta önüne her geleni kapmağa çalışan insanları suçlamam.', 1),
(251,'Kendimi kaybedip yaptığım işi aksattığım ve etrafımda olup bitenlerin farkında olmadığım zamanlar oldu.', 1),
(252,'Hiç kimse başkasının derdine aldırış etmiyor.', 1),
(253,'Hatalı davranışlarını görsem bile insanlara arkadaşça davranabilirim.', 6),
(254,'Birbiriyle şakalaşan kimseler arasında olmayı severim.', 6),
(255,'Seçimlerde bazen oyumu pek az tanıdığım kimselere veririm.', 1),
(256,'Gazetelerin ilgi çeken tek yeri resimli mizah sayfasıdır.', 1),
(257,'Yaptığım işlerde genel olarak başarı elde edeceğime inanırım.', 1),
(258,'Allah’ın varlığına inanırım.', 1),
(259,'İşe başlamada güçlük çekerim.', 1),
(260,'Okulda iken ağır öğrenenlerden biri idim.', 1),
(261,'Ressam olsaydım çiçek resimleri yapardım.', 1),
(262,'Daha güzel olmamam beni rahatsız etmez.', 1),
(263,'Soğuk günlerde bile kolayca terlerim.', 3),
(264,'Kendime tam anlamıyla güvenim vardır.', 5),
(265,'Hiç kimseye güvenmemek en doğrusudur.', 1),
(266,'Haftada bir ya da daha sık; çok heyecanlanırım.', 5),
(267,'Topluluk içinde olduğumda üzerinde konuşacak uygun konular bulmakta güçlük çekerim.', 6),
(268,'Karamsar olduğum zaman heyecanlı bir olay hemen beni bu durumdan çıkarır.', 5),
(269,'Bazen zevk için başkalarını kendimden korkuturum.', 1),
(270,'Evden çıkarken kapının kilitli ve pencerenin kapalı olup olmadığı aklıma takılmaz.', 1),
(271,'Başkalarının saflığını kendi çıkarlarına kullanan kimseleri ayıplamam.', 1),
(272,'Bazen kendimi enerji dolu hissederim.', 5),
(273,'Derimin bazı yerlerinde uyuşukluk hissederim.', 3),
(274,'Görme gücüm eskisi kadar kuvvetlidir.', 3),
(275,'Birisi zihnimi kontrol ediyor.', 1),
(276,'Çocukları severim.', 1),
(277,'Bazen bir madrabazın (Hilecinin) kurnazlığı beni o kadar eğlendirir ki yakayı ele vermemesini dilerim.', 1),
(278,'Çok defa tanımadığım kimselerin bana eleştirici bir gözle baktıklarını hissederim.', 6),
(279,'Her gün gereğinden fazla su içerim.', 3),
(280,'Birçok kimseler kendilerine yararı dokunacağı için arkadaş edinirler.', 1),
(281,'Kulaklarım çok az çınlar ya da uğuldar.', 3),
(282,'1likle sevdiğim aile üyelerine karşı bazen nefret duyarım.', 2),
(283,'Gazete muhabiri olsaydım en çok spor haberleri yazmayı isterdim.', 1),
(284,'Hakkımda çok konuşulduğundan eminim.', 1),
(285,'Arasıra açık saçık bir fıkraya güldüğüm olur.', 1),
(286,'En çok yalnız olduğum zaman mutlu olurum.', 5),
(287,'Arkadaşlarıma kıyasla beni korkutan şeyler çok azdır.', 5),
(288,'Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.', 3),
(289,'Bir suçlu avukatın becerikliliği sayesinde cezadan kurtulunca kanunlara karşı daima nefret duyarım.', 1),
(290,'Çok gergin bir hava içinde çalışıyorum.', 5),
(291,'Hayatımda bir ya da birkaç kere birisinin beni hipnotize ederek bana bir şeyler yaptığını hissettim.', 1),
(292,'Başkaları benimle konuşuncaya kadar ben onlarla konuşmağa başlamam.', 6),
(293,'Birisi zihnimi etkilemeye çalışıyor.', 1),
(294,'Kanunla hiç başım derde girmedi.', 1),
(295,'Masal okumayı severim.', 1),
(296,'Hiçbir neden yokken kendimi son derece neşeli hissettiğim zamanlar olur.', 5),
(297,'Cinsiyetle ilgili düşünceler beni rahatsız eder.', 4),
(298,'Birkaç kişinin birlikte başları derde girince en iyisi yakalarını kurtarmak için aynı hikayeyi uydurmak ve bundan caymamaktır.', 1),
(299,'Duygularımın birçok kimselerden yoğun olduğunu düşünürüm.', 5),
(300,'Hayatımda hiçbir zaman bebekle oynamaktan hoşlanmadım.', 1),
(301,'Çoğu zaman hayat benim için bir yüktür.', 5),
(302,'Cinsel davranışlarımdan dolayı hiçbir zaman başım derde girmedi.', 4),
(303,'Bazı konularda o kadar alınganım ki onlar hakkında konuşmam bile.', 5),
(304,'Okulda sınıf karşısında konuşmak bana çok güç gelirdi.', 6),
(305,'Başkalarıyla beraber olduğum zaman bile kendimi yalnız hissederim.', 6),
(306,'Bana karşı mümkün olan anlayış gösteriliyor.', 1),
(307,'İyi beceremediğim oyunları oynamaya yanaşmam.', 1),
(308,'Zaman zaman evi bırakıp gitmeyi çok istemişimdir.', 1),
(309,'Birçokları kadar çabuk arkadaş edinebildiğimi sanıyorum.', 6),
(310,'Cinsel hayatım doyurucudur.', 4),
(311,'Gençlik yıllarımda bir devre ufak tefek şeyler çaldım.', 1),
(312,'İnsanların arasında olmaktan hiç hoşlanmam.', 6),
(313,'Değerli eşyasını tedbirsizce ortada bırakıp çalınmasına neden olan kimse bunu çalan kadar hatalıdır.', 1),
(314,'Arasıra söylenemeyecek kadar kötü şeyler düşünürüm.', 1),
(315,'Hayatın hep kötü tarafları bana nasip olmuştur.', 1),
(316,'Hemen hemen herkesin başını derde sokmamak için yalan söyleyebileceğine inanırım.', 1),
(317,'Birçok kimselerden daha hassasım.', 5),
(318,'Günlük hayatım beni ilgilendiren şeylerle dolu.', 1),
(319,'İnsanların çoğu başkalarına yardım etmek için zahmete girmekten hoşlanmazlar.', 1),
(320,'Rüyalarımın çoğu cinsel konularla ilgilidir.', 4),
(321,'Kolaylıkla mahcup olurum.', 5),
(322,'Para ve işi kendime dert ederim.', 5),
(323,'Başımdan çok tuhaf ve acayip olaylar geçmiştir.', 1),
(324,'Hiç kimseye aşık olmadım.', 4),
(325,'2min yaptığı bazı şeyler beni korkutmuştur.', 2),
(326,'Bazen kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.', 1),
(327,'Annem ya da babam çok defa beni makul bulmadığım emirlere bile itaat ettirdiler.', 2),
(328,'Zihnimi bir konu ya da iş üzerinde toplamakta güçlük çekerim.', 1),
(329,'Hemen hemen hiç rüya görmedim.', 1),
(330,'Hiç felç geçirmedim ya da kaslarımda olağanüstü bir halsizlik duymadım.', 3),
(331,'Eğer insanlar sırf düşmanlık olsun diye beni engellemeselerdi daha başarılı olurdum.', 1),
(332,'Bazen nezle olmadığım halde sesim çıkmaz ya da değişir.', 3),
(333,'Beni hiç kimse anlamıyor.', 1),
(334,'Bazen tuhaf kokular duyarım.', 1),
(335,'Zihnimi bir konu üzerinde toplayamam.', 1),
(336,'İnsanlara karşı sabrım çabuk tükenir.', 1),
(337,'Çoğunlukla bir takım şeyler ve kimseler için meraklanıp huzursuzlanırım.', 5),
(338,'Hayatımın çoğu kimselerinkinden daha fazla tasa ve kaygı içinde geçtiğine eminim.', 5),
(339,'Çoğu zaman ölmüş olmayı isterdim.', 5),
(340,'Bazen o kadar heyecanlanırım ki uykuya dalmam güçleşir.', 3),
(341,'Bazen beni rahatsız edecek kadar iyi işitirim.', 3),
(342,'Bana söylenenleri hemen unuturum.', 1),
(343,'Önemsiz ufak şeylerde bile karar verip işe girişmeden önce durur ve düşünürüm.', 1),
(344,'Gördüğüm kimse ile karşılaşmamak için sıklıkla yolumu değiştiririm.', 6),
(345,'Sıklıkla olup bitenler bana gerçek değilmiş gibi gelir.', 1),
(346,'Reklamlardaki ampuller gibi önemsiz şeyleri sayma alışkanlığım vardır.', 1),
(347,'Bana gerçekten kötülük yapmak isteyen hiçbir düşmanım yoktur.', 1),
(348,'Bana umduğumdan fazla dostluk gösteren insanlara karşı tetikte bulunmağa çalışırım.', 6),
(349,'Acayip ve tuhaf düşüncelerim vardır.', 1),
(350,'Yalnızken garip şeyler duyarım.', 1),
(351,'Küçük bir seyahat için bile evden ayrılırken telaşlanır ve kaygılanırım.', 5),
(352,'Beni incitmeyeceğini bildiğim şeylerden ya da insanlardan bile korktuğum oldu.', 5),
(353,'Başkalarının daha önce toplanıp konuştuğu odaya girmekten çekinmem.', 6),
(354,'Bıçak gibi çok keskin ve sivri şeyler kullanmaktan korkarım.', 5),
(355,'Sevdiğim kimseleri bazen incitmekten hoşlanırım.', 1),
(356,'Dikkatimi bir konu üzerinde toplamada birçok kişiden daha fazla güçlük çekerim.', 1),
(357,'Yeteneğimi küçümsediğim için birçok defalar başladığım işi yarıda bıraktım.', 5),
(358,'Kötü ve çok defa korkunç kelimeler zihnimi kurcalar ve bunlardan kendimi kurtaramam.', 1),
(359,'Bazen önemsiz düşünceler aklımdan geçer ve beni günlerce rahatsız eder.', 1),
(360,'Hemen hemen her gün beni korkutan bir şey olur.', 5),
(361,'Her şeyi kötüye yorma eğilimindeyim.', 1),
(362,'Birçok kimselerden çok daha hassasım.', 5),
(363,'Bazen sevdiğim kimselerin beni incitmesinden hoşlandığım oldu.', 1),
(364,'Hakkımda onur kırıcı ve kötü sözler söylüyorlar.', 1),
(365,'Kapalı yerlerde huzursuzluk duyarım.', 5),
(366,'İnsanlar arasında bile olsam çok defa kendimi yalnız hissederim.', 6),
(367,'Yangından korkmam.', 5),
(368,'Sonradan pişman olacağım şeyler yapmak ya da söylemek korkusuyla bazen bir kimseden uzak durduğum oldu.', 5),
(369,'Kararsızlığım yüzünden yapılması gerekli birçok işi yapamamışımdır.', 1),
(370,'Çalışırken acele etmek zorunda olmaktan nefret ederim.', 1),
(371,'Aşırı derecede kendini dinleyen bir insan değilim.', 1),
(372,'Elimdeki işi en iyi şekilde yapmayı isterim.', 1),
(373,'Yalnızca bir tek doğru din olduğundan eminim.', 1),
(374,'Ara sıra zihnim her zamankinden daha ağır işler.', 1),
(375,'Çok mutlu olduğum ve iyi çalıştığım zamanlarda neşesiz veya dertli bir insanla karşılaşmak keyfimi tamamen kaçırır.', 6),
(376,'Polisler genellikle dürüsttür.', 1),
(377,'Toplantılarda kalabalığa karışmaktan çok yalnız başıma oturur ya da bir tek kişiyle ahbaplık ederim.', 6),
(378,'Kadınları sigara içerken görmekten hoşlanmam.', 1),
(379,'Çok nadiren karamsarlığa kapılırım.', 5),
(380,'Ne yapsam zevk alamıyorum.', 5),
(381,'Kolay öfkelenen biri olduğumu söylerler.', 1),
(382,'Yapmak istediğim şeylere karar verirken; başkalarının ne düşüneceğini dikkate almam.', 1),
(383,'İnsanlar çoğu zaman beni hayal kırıklığına uğratırlar.', 1),
(384,'Kendimle ilgili her şeyi anlatabileceğim hiç kimse yok.', 6),
(385,'Şimşek çakması da korkularımdan biridir.', 5),
(386,'Çok tertipli ve titizim.', 1),
(387,'2m her davranışıma fazla karışıyor.', 2),
(388,'Karanlıkta yalnız kalmaktan korkarım.', 5),
(389,'Tasarlamış olduğum planlar çok defa o kadar güçlükle dolu göründü ki bunlardan vazgeçmek zorunda kaldım.', 1),
(390,'Birinin hatasını önleme gayretimin yanlış anlaşılmasına çok üzülürüm.', 1),
(391,'Dansa gitmeyi severim.', 1),
(392,'Fırtınadan çok korkarım.', 5),
(393,'Yük çekmeyen atlar dövülmeli ya da kamçılanmalıdır.', 1),
(394,'Başkalarına sık sık akıl danışırım.', 6),
(395,'Gelecek; bir insanın ciddi planlar yapamayacağı kadar belirsizdir.', 1),
(396,'İşler yolunda gittiği zaman bile çoğu kez her şeye karşı bir aldırmazlık içinde olduğumu hissederim.', 5),
(397,'Bazen güçlükler öylesine üst üste gelir ki onlarla baş edemeyecekmişim gibi hissederim.', 5),
(398,'Çoğu kez “Keşke tekrar çocuk olsaydım” diye düşünürüm.', 1),
(399,'Kolay kolay kızmam.', 1),
(400,'Eğer bana fırsat verilse dünya için çok yararlı işler yapabilirim.', 1),
(401,'Sudan hiç korkmam.', 5),
(402,'Ne yapacağıma karar vermeden önce uzun uzun düşünürüm.', 1),
(403,'Birçok şeyin olup bittiği böyle bir devirde yaşamak hoş bir şey.', 1),
(404,'Hatalarını düzelterek kendilerine yardım etmeye çalıştığım insanlar amacımı çoğu kez yanlış anlarlar.', 1),
(405,'Yutkunmakta güçlük çekmem.', 3),
(406,'Uzman dendiği halde benden pek fazla bilgili olmayan insanlarla sıklıkla karşılaşırım.', 1),
(407,'1 olarak sakinim ve kolay sinirlenmem.', 1),
(408,'Bazı konular hakkında hislerimi o kadar gizleyebilirim ki insanlar bilmeden beni incitebilirler.', 6),
(409,'Elimde olmadan çok ufak bir şeyden münakaşa çıkarıp karşımdakini kırıyorum.', 1),
(410,'Madrabazı (hilekarı) kendi silahı ile alt etmekten hoşlanırım.', 1),
(411,'İyi tanıdığım bir kimsenin başarısını duyduğum zaman adeta kendimi başarısızlığa uğramış hissederim.', 5),
(412,'Hastalandığım zaman doktora gitmekten korkmam.', 3),
(413,'Günahlarım için ne kadar ağır ceza görsem iyidir.', 1),
(414,'Hayal kırıklıklarını o kadar ciddiye alırım ki bunları zihnimden söküp atamam.', 5),
(415,'Fırsat verilse iyi bir önder olurum.', 1),
(416,'Yakınlarımın sağlığından çok endişe ederim.', 5),
(417,'Sırada beklerken biri önüme geçmeye kalkışırsa ona çıkışırım.', 1),
(418,'Bazen hiçbir işe yaramadığımı düşünürüm.', 5),
(419,'Küçükken okuldan sık sık kaçardım.', 1),
(420,'Başımdan dinle ilgili olağanüstü yaşantılar geçti.', 1),
(421,'2mde çok sinirli insanlar var.', 2),
(422,'2mde bazı kişilerin yapmış olduğu işler beni utandırmıştır.', 2),
(423,'Balık tutmayı çok severim.', 1),
(424,'Hemen hemen her zaman açlık duyarım.', 3),
(425,'Sık sık rüya görürüm.', 1),
(426,'Kaba ya da can sıkıcı insanlara karşı bazen sert davrandığım olur.', 6),
(427,'Açık saçık hikayelerden utanıp rahatsız olurum.', 1),
(428,'Gazetelerin baş yazılarını okumaktan hoşlanırım.', 1),
(429,'Ciddi konular üzerinde verilen konferansları dinlemekten hoşlanırım.', 1),
(430,'Karşı cinsten olanları çekici bulurum.', 4),
(431,'Başa gelebilecek talihsizlikler beni oldukça telaşlandırır.', 5),
(432,'Kuvvetli siyasi fikirlerim vardır.', 1),
(433,'Bir zamanlar hayali arkadaşlarım vardı.', 1),
(434,'Otomobil yarışçısı olmayı isterdim.', 1),
(435,'1 olarak kadınlarla çalışmayı tercih ederim.', 1),
(436,'İnsanlar genel olarak başkalarının haklarına saygı göstermekten çok kendi haklarına saygı gösterilmesini isterler.', 1),
(437,'Kanuna aykırı davranmadan kanunun bir gediğinden yararlanmakta zarar yoktur.', 1),
(438,'Bazı insanlardan o kadar nefret ederim ki ettiklerini bulunca içimden oh derim.', 1),
(439,'Beklemek zorunda kalmak beni sinirlendirir.', 1),
(440,'Başkalarına anlatmak için hoş fıkraları hatırımda tutmaya çalışırım.', 1),
(441,'Uzun boylu kadınlardan hoşlanırım.', 1),
(442,'Üzüntü yüzünden uyuyamadığım zamanlar oldu.', 5),
(443,'Başkalarının gereği gibi yapamadığımı sandığı şeyleri yapmaktan vazgeçtiğim oldu.', 1),
(444,'Başkalarının cahilce inançlarını düzeltmeye çalışmam.', 1),
(445,'Küçükken heyecan veren şeyler yapmaktan hoşlanırdım.', 1),
(446,'Az parayla oynanan kumardan hoşlanırım.', 1),
(447,'Mastürbasyonda kendi cinsimle ilgili hayal beni tahrik eder.', 4),
(448,'Sokakta; otobüs ve dükkanlarda bana bakan insanlardan rahatsız olurum.', 6),
(449,'İnsanlarla bir arada olmayı sağladığı için toplantı ve davetleri severim.', 6),
(450,'Kalabalığın verdiği coşkudan hoşlanırım.', 6),
(451,'Neşeli arkadaşlar arasına karışınca üzüntülerimi unuturum.', 5),
(452,'Arkadaş edinemiyorum.', 6),
(453,'Küçükken mahalledeki arkadaş ya da akran gruplarına katılmaktan hoşlanmazdım.', 6),
(454,'Orman ya da dağdaki bir kulübede tek başıma yaşamaktan mutlu olabilirim.', 6),
(455,'İçinde bulunduğum grubun dedikodularına ve konuşmalarına sıklıkla konu olmam.', 6),
(456,'İnsan makul bulmadığı kanunlara aykırı hareketlerinden ötürü cezalandırılmamalıdır.', 1),
(457,'Bence insan hiçbir zaman alkollü bir içkiyi ağzına almamalıdır.', 1),
(458,'Çocukken benimle en fazla ilgilenen erkek (baba; üvey baba vb.) bana karşı çok sert davrandı.', 2),
(459,'Çaba göstermekle yenemeyeceğimi bildiğim bazı kötü alışkanlıklarım var.', 1),
(460,'Az içki kullandım ya da hiç kullanmadım.', 1),
(461,'Kısa bir zaman için bile olsa başladığım işi bir kenara bırakmak bana güç gelir.', 1),
(462,'Küçük abdestimi yapmada ya da tutmada güçlük çekmem.', 3),
(463,'Seksek oyunu oynamaktan hoşlanırdım.', 1),
(464,'Hiç hayal görmedim.', 1),
(465,'Birkaç kez hayatım boyunca yaptığım işte hevesimi yitirdiğim olmuştur.', 1),
(466,'Doktor önerisi dışında hiçbir ilaç ya da uyku hapı kullanmadım.', 3),
(467,'Çok defa (otomobil; plaka numarası gibi) hiç önemli olmayan numaraları ezberlerim.', 1),
(468,'Sıklıkla sinirli ve asık suratlı olurum.', 5),
(469,'Onlardan önce düşündüğüm için başkaları benim fikirlerimi kıskanıyorlar.', 1),
(470,'Cinsiyetle ilgili şeylerden nefret ederim.', 4),
(471,'Okulda hal ve gidişten kırık not alırdım.', 1),
(472,'Yangın karşısında büyülenmiş gibi olurum.', 1),
(473,'Mümkün olduğu kadar kalabalıktan uzak kalmaya çalışırım.', 6),
(474,'Başkalarından daha sık küçük abdeste çıkmam.', 3),
(475,'Sıkıştırıldığım zaman gerçeğin ancak bana zarar vermeyeceği kısmını söylerim.', 1),
(476,'Tanrı bana özel bir görev vermiştir.', 1),
(477,'Arkadaşlarımla birlikte işlediğim bir suçtan eşit şekilde suçlu olduğum zaman onları ele vermektense bütün suçu üzerime almayı tercih ederim.', 1),
(478,'Çok değişik bir aile ortamından gelmiş olmayı isterdim.', 2),
(479,'Yabancılarla tanışmaktan kaçınmam.', 6),
(480,'Karanlıktan çok defa korkarım.', 5),
(481,'Bir şeyden kurtulmak için hasta numarası yaptığım olmuştur.', 1),
(482,'Trende; otobüste vb. rastladığım kimselerle çok defa konuşurum.', 6),
(483,'Peygamberimiz göğe çıkma gibi mucizeler göstermiştir.', 1),
(484,'Homoseksüelliği çok iğrenç buluyorum.', 4),
(485,'Bir erkek bir kadınla beraber olunca genel olarak onun cinsiyetiyle ilgili şeyler düşünür.', 4),
(486,'İdrarımda hiçbir zaman kan görmedim.', 3),
(487,'Uğraştığım iş yolunda gitmeyince hemen vazgeçerim.', 1),
(488,'Sık sık dua ederim.', 1),
(489,'Yaşamı yalnızca üzüntülü; sıkıntılı tarafları ile benimseyen insanlara sempati duyarım.', 1),
(490,'Haftada birkaç kere Kur’an okurum.', 1),
(491,'Sadece bir tek dinin doğruluğuna inananlara tahammül edemem.', 1),
(492,'Zelzele düşüncesi beni çok korkutur.', 5),
(493,'Tam dikkat isteyen işleri; beni dikkatsizliğe sürükleyen işlere tercih ederim.', 1),
(494,'Kapalı ve küçük yerlerde bulunmaktan çok rahatsız olurum.', 5),
(495,'Kusurlarını düzeltmeye çalıştığım insanlarla genel olarak gayet açık konuşurum.', 6),
(496,'Eşyayı hiçbir zaman çift görmem (Yani tek olan şeyleri çift görmem.)', 3),
(497,'Macera hikayelerinden hoşlanırım.', 1),
(498,'Açık sözlü olmak her zaman iyidir.', 1),
(499,'Gerçekten önemsiz olan bir şey üzerinde bazen sebepsiz olarak haddinden fazla üzüldüğüm olur.', 1),
(500,'Bana parlak gelen bir fikre hemen kapılır giderim.', 1),
(501,'Başkalarından yardım beklemektense genel olarak bir işi kendi başıma yapmayı tercih ederim.', 6),
(502,'Herhangi bir olay hakkındaki görüşümü başkalarına açıkça belirtmekten hoşlanırım.', 6),
(503,'Başkalarının hareketlerini çok beğenip beğenmediğimi pek belli etmem.', 1),
(504,'Değersiz gördüğüm ya da acıdığım kimseye bu duygularımı belli etmem.', 6),
(505,'Zaman zaman kendimi öyle güçlü ve enerjik hissederim ki böyle zamanlarda günlerce uykuya ihtiyaç duymadığım olur.', 1),
(506,'Sinirleri çok gergin bir insanım.', 5),
(507,'İşler iyi gidince aslan payını kendilerine alan fakat hata yapılınca bunu başkalarının üzerine atan insanlarla karşılaştım.', 1),
(508,'Koku alma duyum herkes kadar iyidir.', 3),
(509,'Bazen çekingenliğim yüzünden hakkımı arayamam.', 6),
(510,'Pislik ve kir beni ürkütüp iğrendirir.', 1),
(511,'Herkesten gizli tuttuğum bir hayal dünyam var.', 1),
(512,'Yıkanmaktan hoşlanmam.', 1),
(513,'Kış mevsimini severim.', 1),
(514,'Erkek gibi davranan kadınlardan hoşlanırım.', 1),
(515,'Evimizde daima gerekli ihtiyaç maddeleri bulunurdu (yeteri kadar yiyecek; giyecek vs. gibi).', 1),
(516,'2mde çabuk kızan kimseler var.', 2),
(517,'Hiçbir şeyi iyi yapamam.', 5),
(518,'Bazı durumlarda olduğumdan daha fazla üzüntülü görünmeye çalıştığım olmuştur.', 1),
(519,'Cinsel organlarımda bir bozukluk var.', 4),
(520,'1 olarak görüşlerimi kuvvetle savunurum.', 6),
(521,'Bir grup içinde konuşma yapmam ve çok iyi bildiğim bir konuda fikrimi söylemem istenince kaygılanmam.', 6),
(522,'Örümcekten korkmam.', 5),
(523,'Yüzüm hemen hemen hiç kızarmaz.', 3),
(524,'Kapı tokmaklarından hastalık veya mikrop alacağımdan korkmam.', 5),
(525,'Bazı hayvanlardan ürkerim.', 5),
(526,'Gelecek bana ümitsiz görünüyor.', 5),
(527,'2m ve yakın akrabalarım birbirleri ile oldukça iyi geçinirler.', 2),
(528,'Yüzüm başkalarından daha sık kızarmaz.', 3),
(529,'Pahalı elbiseler giymeyi isterim.', 1),
(530,'Sebepsiz yere sık sık içim sıkılıyor ve ağlamak istiyorum.', 5),
(531,'Bir konu üzerinde karar verdiğimi zannetsem bile başka biri fikrimi kolayca değiştirebilir.', 1),
(532,'Acıya başkaları kadar ben de dayanabilirim.', 3),
(533,'Sık sık geğirmekten şikayetim yoktur.', 3),
(534,'Çoğunlukla başladığım işten en son vazgeçen ben olurum.', 1),
(535,'Hemen hemen her zaman ağzımda kuruluk olur.', 3),
(536,'Beni acele ettirenlere kızarım.', 1),
(537,'Afrika’da aslan avına çıkmak isterdim.', 1),
(538,'Terzilikten hoşlanabileceğimi sanmıyorum.', 1),
(539,'Fareden korkmam.', 5),
(540,'Yüzüme hiç felç inmedi.', 3),
(541,'Cildime ufak bir şeyin dokunmasından çok huylanırım.', 3),
(542,'Şimdiye kadar rengi kapkara büyük abdest yapmadım.', 3),
(543,'Haftada birkaç kez korkunç bir şey olacakmış duygusuna kapılırım.', 5),
(544,'Çoğu zaman yorgunluk hissederim.', 3),
(545,'Bazen aynı rüyayı tekrar tekrar görürüm.', 1),
(546,'Tarih okumaktan hoşlanırım.', 1),
(547,'Toplantı ve kalabalık eğlencelerden hoşlanırım.', 6),
(548,'Elimdeyse açık saçık numaraların yapılacağı eğlence yerlerine gitmem.', 1),
(549,'Karşıma çıkacak güçlüklerden korkar ve kaçarım.', 5),
(550,'Kapı mandallarını onarmaktan hoşlanırım.', 1),
(551,'Bazen başkalarının kafamın içindekileri okuduğundan eminim.', 1),
(552,'Bilimsel yayınları okumaktan hoşlanırım.', 1),
(553,'Açık yerlerde veya geniş meydanlarda tek başıma kalmaktan korkarım.', 5),
(554,'Sıkıntım oldukça alkol alırım.', 1),
(555,'Bazen çıldıracakmış gibi olurum.', 5),
(556,'Kılık kıyafetime çok dikkat ederim.', 1),
(557,'Hayatı fazla ciddiye almıyorum.', 1),
(558,'Birçok kimseler kötü cinsel faaliyetlerinden dolayı suçludurlar.', 4),
(559,'Gece yarısı çoğunlukla korkuya kapıldığım olur.', 5),
(560,'Bir şeyi nereye koyduğumu unutmaktan çok şikayetçiyimdir.', 1),
(561,'2m benim için büyük bir dayanaktır.', 2),
(562,'Çocukken en fazla bağlandığım ve hayran kaldığım kimse bir kadındı.', 1),
(563,'Macera hikayelerini aşk hikayelerinden daha çok severim.', 1),
(564,'Yapmak istediğim fakat başkalarının beğenmediği bir işten kolayca vazgeçerim.', 6),
(565,'Yüksek bir yerde iken içimden atlama isteği gelir.', 5),
(566,'Sinemalardaki aşk sahnelerini severim.', 4)

ON CONFLICT (question_number) DO UPDATE SET question_text = EXCLUDED.question_text, category_id = EXCLUDED.category_id;

-- Note: question 101-566 are in dokumanlar/questions_insert.sql
-- This file contains all 566 questions. Run the full file if needed:
-- \i ../dokumanlar/questions_insert.sql

-- ============================================================
-- 2. SCORING KEYS
-- Source: dokumanlar/scoring_keys_insert.sql
-- ============================================================
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
-- L Scale Doğru 1
('L', 96, 'Doğru'),
-- L Scale Yanlış 15 
('L', 15, 'Yanlış'), ('L', 30, 'Yanlış'), ('L', 45, 'Yanlış'),
('L', 60, 'Yanlış'), ('L', 75, 'Yanlış'), ('L', 90, 'Yanlış'),
('L', 105, 'Yanlış'), ('L', 120, 'Yanlış'), ('L', 135, 'Yanlış'),
('L', 150, 'Yanlış'), ('L', 165, 'Yanlış'), ('L', 195, 'Yanlış'),
('L', 225, 'Yanlış'), ('L', 255, 'Yanlış'), ('L', 285, 'Yanlış'),
-- F Scale (Dogru) 44
('F', 14, 'Doğru'), ('F', 23, 'Doğru'), ('F', 27, 'Doğru'),
('F', 31, 'Doğru'), ('F', 34, 'Doğru'), ('F', 35, 'Doğru'),
('F', 40, 'Doğru'), ('F', 42, 'Doğru'), ('F', 48, 'Doğru'),
('F', 49, 'Doğru'), ('F', 50, 'Doğru'), ('F', 53, 'Doğru'),
('F', 56, 'Doğru'), ('F', 66, 'Doğru'), ('F', 85, 'Doğru'),
('F', 121, 'Doğru'), ('F', 123, 'Doğru'), ('F', 139, 'Doğru'),
('F', 146, 'Doğru'), ('F', 151, 'Doğru'), ('F', 156, 'Doğru'),
('F', 168, 'Doğru'), ('F', 184, 'Doğru'), ('F', 197, 'Doğru'),
('F', 200, 'Doğru'), ('F', 202, 'Doğru'), ('F', 205, 'Doğru'),
('F', 206, 'Doğru'), ('F', 209, 'Doğru'), ('F', 210, 'Doğru'),
('F', 211, 'Doğru'), ('F', 215, 'Doğru'), ('F', 218, 'Doğru'),
('F', 227, 'Doğru'), ('F', 245, 'Doğru'), ('F', 246, 'Doğru'),
('F', 247, 'Doğru'), ('F', 252, 'Doğru'), ('F', 256, 'Doğru'),
('F', 269, 'Doğru'), ('F', 275, 'Doğru'), ('F', 286, 'Doğru'),
('F', 291, 'Doğru'), ('F', 293, 'Doğru'),
-- F Scale (Yanlış) 20
('F', 17, 'Yanlış'), ('F', 20, 'Yanlış'), ('F', 54, 'Yanlış'),
('F', 65, 'Yanlış'), ('F', 75, 'Yanlış'), ('F', 83, 'Yanlış'),
('F', 112, 'Yanlış'), ('F', 113, 'Yanlış'), ('F', 115, 'Yanlış'),
('F', 164, 'Yanlış'), ('F', 169, 'Yanlış'), ('F', 177, 'Yanlış'),
('F', 185, 'Yanlış'), ('F', 196, 'Yanlış'), ('F', 199, 'Yanlış'),
('F', 220, 'Yanlış'), ('F', 257, 'Yanlış'), ('F', 258, 'Yanlış'),
('F', 272, 'Yanlış'), ('F', 276, 'Yanlış'),
-- K Scale Doğru 1
('K', 96, 'Doğru'),
-- K Scale Yanlış 29
('K', 30, 'Yanlış'), ('K', 39, 'Yanlış'), ('K', 71, 'Yanlış'),
('K', 89, 'Yanlış'), ('K', 124, 'Yanlış'), ('K', 129, 'Yanlış'),
('K', 134, 'Yanlış'), ('K', 138, 'Yanlış'), ('K', 142, 'Yanlış'),
('K', 148, 'Yanlış'), ('K', 160, 'Yanlış'), ('K', 170, 'Yanlış'),
('K', 171, 'Yanlış'), ('K', 180, 'Yanlış'), ('K', 183, 'Yanlış'),
('K', 217, 'Yanlış'), ('K', 234, 'Yanlış'), ('K', 267, 'Yanlış'),
('K', 272, 'Yanlış'), ('K', 296, 'Yanlış'), ('K', 316, 'Yanlış'),
('K', 322, 'Yanlış'), ('K', 374, 'Yanlış'), ('K', 383, 'Yanlış'),
('K', 397, 'Yanlış'), ('K', 398, 'Yanlış'), ('K', 406, 'Yanlış'),
('K', 461, 'Yanlış'), ('K', 502, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Hs Scale (Hipokondriazis)
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
-- Hs Scale Doğru 11
('Hs', 23, 'Doğru'), ('Hs', 29, 'Doğru'), ('Hs', 43, 'Doğru'),
('Hs', 62, 'Doğru'), ('Hs', 72, 'Doğru'), ('Hs', 108, 'Doğru'),
('Hs', 114, 'Doğru'), ('Hs', 125, 'Doğru'), ('Hs', 161, 'Doğru'),
('Hs', 189, 'Doğru'), ('Hs', 273, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
-- Hs Scale Yanlış 22
('Hs', 2, 'Yanlış'), ('Hs', 3, 'Yanlış'), ('Hs', 7, 'Yanlış'),
('Hs', 9, 'Yanlış'), ('Hs', 18, 'Yanlış'), ('Hs', 51, 'Yanlış'),
('Hs', 55, 'Yanlış'), ('Hs', 63, 'Yanlış'), ('Hs', 68, 'Yanlış'),
('Hs', 103, 'Yanlış'), ('Hs', 130, 'Yanlış'), ('Hs', 153, 'Yanlış'),
('Hs', 155, 'Yanlış'), ('Hs', 163, 'Yanlış'), ('Hs', 175, 'Yanlış'),
('Hs', 188, 'Yanlış'), ('Hs', 190, 'Yanlış'), ('Hs', 192, 'Yanlış'),
('Hs', 230, 'Yanlış'), ('Hs', 243, 'Yanlış'), ('Hs', 274, 'Yanlış'),
('Hs', 281, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- D Scale (Depresyon)
-- D Scale Doğru 20
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('D', 5, 'Doğru'), ('D', 13, 'Doğru'), ('D', 23, 'Doğru'),
('D', 32, 'Doğru'), ('D', 41, 'Doğru'), ('D', 43, 'Doğru'),
('D', 52, 'Doğru'), ('D', 67, 'Doğru'), ('D', 86, 'Doğru'),
('D', 104, 'Doğru'), ('D', 130, 'Doğru'), ('D', 138, 'Doğru'),
('D', 142, 'Doğru'), ('D', 158, 'Doğru'), ('D', 159, 'Doğru'),
('D', 182, 'Doğru'), ('D', 189, 'Doğru'), ('D', 193, 'Doğru'),
('D', 236, 'Doğru'), ('D', 259, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;
-- D Scale Yanlış 40
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('D', 2, 'Yanlış'), ('D', 8, 'Yanlış'), ('D', 9, 'Yanlış'),
('D', 18, 'Yanlış'), ('D', 30, 'Yanlış'), ('D', 36, 'Yanlış'),
('D', 39, 'Yanlış'), ('D', 46, 'Yanlış'), ('D', 51, 'Yanlış'),
('D', 57, 'Yanlış'), ('D', 58, 'Yanlış'), ('D', 64, 'Yanlış'),
('D', 80, 'Yanlış'), ('D', 88, 'Yanlış'), ('D', 89, 'Yanlış'),
('D', 95, 'Yanlış'), ('D', 98, 'Yanlış'), ('D', 107, 'Yanlış'),
('D', 122, 'Yanlış'), ('D', 131, 'Yanlış'), ('D', 145, 'Yanlış'),
('D', 152, 'Yanlış'), ('D', 153, 'Yanlış'), ('D', 154, 'Yanlış'),
('D', 155, 'Yanlış'), ('D', 160, 'Yanlış'), ('D', 178, 'Yanlış'),
('D', 191, 'Yanlış'), ('D', 207, 'Yanlış'), ('D', 208, 'Yanlış'),
('D', 233, 'Yanlış'), ('D', 241, 'Yanlış'), ('D', 242, 'Yanlış'),
('D', 248, 'Yanlış'), ('D', 263, 'Yanlış'), ('D', 270, 'Yanlış'),
('D', 271, 'Yanlış'), ('D', 272, 'Yanlış'), ('D', 285, 'Yanlış'),
('D', 296, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Hy Scale (Histeri)
-- Hy Scale Doğru 13
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Hy', 10, 'Doğru'), ('Hy', 23, 'Doğru'), ('Hy', 32, 'Doğru'),
('Hy', 43, 'Doğru'), ('Hy', 44, 'Doğru'), ('Hy', 47, 'Doğru'),
('Hy', 76, 'Doğru'), ('Hy', 114, 'Doğru'), ('Hy', 179, 'Doğru'),
('Hy', 186, 'Doğru'), ('Hy', 189, 'Doğru'), ('Hy', 238, 'Doğru'),
('Hy', 253, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;
-- Hy Scale Yanlış 47
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Hy', 2, 'Yanlış'), ('Hy', 3, 'Yanlış'), ('Hy', 6, 'Yanlış'),
('Hy', 7, 'Yanlış'), ('Hy', 8, 'Yanlış'), ('Hy', 9, 'Yanlış'),
('Hy', 12, 'Yanlış'), ('Hy', 26, 'Yanlış'), ('Hy', 30, 'Yanlış'),
('Hy', 51, 'Yanlış'), ('Hy', 55, 'Yanlış'), ('Hy', 71, 'Yanlış'),
('Hy', 89, 'Yanlış'), ('Hy', 93, 'Yanlış'), ('Hy', 103, 'Yanlış'),
('Hy', 107, 'Yanlış'), ('Hy', 109, 'Yanlış'), ('Hy', 124, 'Yanlış'),
('Hy', 128, 'Yanlış'), ('Hy', 129, 'Yanlış'), ('Hy', 136, 'Yanlış'),
('Hy', 137, 'Yanlış'), ('Hy', 141, 'Yanlış'), ('Hy', 147, 'Yanlış'),
('Hy', 153, 'Yanlış'), ('Hy', 160, 'Yanlış'), ('Hy', 162, 'Yanlış'),
('Hy', 163, 'Yanlış'), ('Hy', 170, 'Yanlış'), ('Hy', 172, 'Yanlış'),
('Hy', 174, 'Yanlış'), ('Hy', 175, 'Yanlış'), ('Hy', 180, 'Yanlış'),
('Hy', 188, 'Yanlış'), ('Hy', 190, 'Yanlış'), ('Hy', 192, 'Yanlış'),
('Hy', 201, 'Yanlış'), ('Hy', 213, 'Yanlış'), ('Hy', 230, 'Yanlış'),
('Hy', 234, 'Yanlış'), ('Hy', 243, 'Yanlış'), ('Hy', 265, 'Yanlış'),
('Hy', 267, 'Yanlış'), ('Hy', 274, 'Yanlış'), ('Hy', 279, 'Yanlış'),
('Hy', 289, 'Yanlış'), ('Hy', 292, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Pd Scale (Psikopatik Sapma)
-- Pd Doğru 24
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pd', 16, 'Doğru'), ('Pd', 21, 'Doğru'), ('Pd', 24, 'Doğru'),
('Pd', 32, 'Doğru'), ('Pd', 33, 'Doğru'), ('Pd', 35, 'Doğru'),
('Pd', 38, 'Doğru'), ('Pd', 42, 'Doğru'), ('Pd', 61, 'Doğru'),
('Pd', 67, 'Doğru'), ('Pd', 84, 'Doğru'), ('Pd', 94, 'Doğru'),
('Pd', 102, 'Doğru'), ('Pd', 106, 'Doğru'), ('Pd', 110, 'Doğru'),
('Pd', 118, 'Doğru'), ('Pd', 127, 'Doğru'), ('Pd', 215, 'Doğru'),
('Pd', 216, 'Doğru'), ('Pd', 224, 'Doğru'), ('Pd', 239, 'Doğru'),
('Pd', 244, 'Doğru'), ('Pd', 245, 'Doğru'), ('Pd', 284, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;
-- Pd Scale Yanlış 26
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pd', 8, 'Yanlış'), ('Pd', 20, 'Yanlış'), ('Pd', 37, 'Yanlış'),
('Pd', 82, 'Yanlış'), ('Pd', 91, 'Yanlış'), ('Pd', 96, 'Yanlış'),
('Pd', 107, 'Yanlış'), ('Pd', 134, 'Yanlış'), ('Pd', 137, 'Yanlış'),
('Pd', 141, 'Yanlış'), ('Pd', 155, 'Yanlış'), ('Pd', 170, 'Yanlış'),
('Pd', 171, 'Yanlış'), ('Pd', 173, 'Yanlış'), ('Pd', 180, 'Yanlış'),
('Pd', 183, 'Yanlış'), ('Pd', 201, 'Yanlış'), ('Pd', 231, 'Yanlış'),
('Pd', 235, 'Yanlış'), ('Pd', 237, 'Yanlış'), ('Pd', 248, 'Yanlış'),
('Pd', 267, 'Yanlış'), ('Pd', 287, 'Yanlış'), ('Pd', 289, 'Yanlış'),
('Pd', 294, 'Yanlış'), ('Pd', 296, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Mf_Male Scale (Maskülinite-Femininite - Erkek)
-- Mf_Male Doğru 20
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Mf_Male', 4, 'Doğru'), ('Mf_Male', 25, 'Doğru'), ('Mf_Male', 69, 'Doğru'),
('Mf_Male', 70, 'Doğru'), ('Mf_Male', 74, 'Doğru'), ('Mf_Male', 77, 'Doğru'),
('Mf_Male', 78, 'Doğru'), ('Mf_Male', 87, 'Doğru'), ('Mf_Male', 92, 'Doğru'),
('Mf_Male', 126, 'Doğru'), ('Mf_Male', 132, 'Doğru'), ('Mf_Male', 134, 'Doğru'),
('Mf_Male', 140, 'Doğru'), ('Mf_Male', 149, 'Doğru'), ('Mf_Male', 179, 'Doğru'),
('Mf_Male', 187, 'Doğru'), ('Mf_Male', 203, 'Doğru'), ('Mf_Male', 204, 'Doğru'),
('Mf_Male', 217, 'Doğru'), ('Mf_Male', 226, 'Doğru'), ('Mf_Male', 231, 'Doğru'),
('Mf_Male', 239, 'Doğru'), ('Mf_Male', 261, 'Doğru'), ('Mf_Male', 278, 'Doğru'),
('Mf_Male', 282, 'Doğru'), ('Mf_Male', 295, 'Doğru'), ('Mf_Male', 297, 'Doğru'),
('Mf_Male', 299, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;
-- Mf_Male Yanlış 32
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Mf_Male', 1, 'Yanlış'), ('Mf_Male', 19, 'Yanlış'), ('Mf_Male', 26, 'Yanlış'),
('Mf_Male', 28, 'Yanlış'), ('Mf_Male', 79, 'Yanlış'), ('Mf_Male', 80, 'Yanlış'),
('Mf_Male', 81, 'Yanlış'), ('Mf_Male', 89, 'Yanlış'), ('Mf_Male', 99, 'Yanlış'),
('Mf_Male', 112, 'Yanlış'), ('Mf_Male', 115, 'Yanlış'), ('Mf_Male', 116, 'Yanlış'),
('Mf_Male', 117, 'Yanlış'), ('Mf_Male', 120, 'Yanlış'), ('Mf_Male', 133, 'Yanlış'),
('Mf_Male', 144, 'Yanlış'), ('Mf_Male', 176, 'Yanlış'), ('Mf_Male', 198, 'Yanlış'),
('Mf_Male', 213, 'Yanlış'), ('Mf_Male', 214, 'Yanlış'), ('Mf_Male', 219, 'Yanlış'),
('Mf_Male', 221, 'Yanlış'), ('Mf_Male', 223, 'Yanlış'), ('Mf_Male', 229, 'Yanlış'),
('Mf_Male', 249, 'Yanlış'), ('Mf_Male', 254, 'Yanlış'), ('Mf_Male', 260, 'Yanlış'),
('Mf_Male', 262, 'Yanlış'), ('Mf_Male', 264, 'Yanlış'), ('Mf_Male', 280, 'Yanlış'),
('Mf_Male', 283, 'Yanlış'), ('Mf_Male', 300, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Mf_Female Scale (Maskülinite-Femininite - Kadın)
-- Mf_Female Doğru 25
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Mf_Female', 4, 'Doğru'), ('Mf_Female', 25, 'Doğru'), ('Mf_Female', 70, 'Doğru'),
('Mf_Female', 74, 'Doğru'), ('Mf_Female', 77, 'Doğru'), ('Mf_Female', 78, 'Doğru'),
('Mf_Female', 87, 'Doğru'), ('Mf_Female', 92, 'Doğru'), ('Mf_Female', 126, 'Doğru'),
('Mf_Female', 132, 'Doğru'), ('Mf_Female', 133, 'Doğru'), ('Mf_Female', 134, 'Doğru'),
('Mf_Female', 140, 'Doğru'), ('Mf_Female', 149, 'Doğru'), ('Mf_Female', 187, 'Doğru'),
('Mf_Female', 203, 'Doğru'), ('Mf_Female', 204, 'Doğru'), ('Mf_Female', 217, 'Doğru'),
('Mf_Female', 226, 'Doğru'), ('Mf_Female', 239, 'Doğru'), ('Mf_Female', 261, 'Doğru'),
('Mf_Female', 278, 'Doğru'), ('Mf_Female', 282, 'Doğru'), ('Mf_Female', 295, 'Doğru'),
('Mf_Female', 299, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Mf_Female Yanlış 35
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Mf_Female', 1, 'Yanlış'), ('Mf_Female', 19, 'Yanlış'), ('Mf_Female', 26, 'Yanlış'),
('Mf_Female', 28, 'Yanlış'), ('Mf_Female', 69, 'Yanlış'), ('Mf_Female', 79, 'Yanlış'),
('Mf_Female', 80, 'Yanlış'), ('Mf_Female', 81, 'Yanlış'), ('Mf_Female', 89, 'Yanlış'),
('Mf_Female', 99, 'Yanlış'), ('Mf_Female', 112, 'Yanlış'), ('Mf_Female', 115, 'Yanlış'),
('Mf_Female', 116, 'Yanlış'), ('Mf_Female', 117, 'Yanlış'), ('Mf_Female', 120, 'Yanlış'),
('Mf_Female', 144, 'Yanlış'), ('Mf_Female', 176, 'Yanlış'), ('Mf_Female', 179, 'Yanlış'),
('Mf_Female', 198, 'Yanlış'), ('Mf_Female', 213, 'Yanlış'), ('Mf_Female', 214, 'Yanlış'),
('Mf_Female', 219, 'Yanlış'), ('Mf_Female', 221, 'Yanlış'), ('Mf_Female', 223, 'Yanlış'),
('Mf_Female', 229, 'Yanlış'), ('Mf_Female', 231, 'Yanlış'), ('Mf_Female', 249, 'Yanlış'),
('Mf_Female', 254, 'Yanlış'), ('Mf_Female', 260, 'Yanlış'), ('Mf_Female', 262, 'Yanlış'),
('Mf_Female', 264, 'Yanlış'), ('Mf_Female', 280, 'Yanlış'), ('Mf_Female', 283, 'Yanlış'),
('Mf_Female', 297, 'Yanlış'), ('Mf_Female', 300, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Pa Scale (Paranoya)
-- Pa Scale Doğru 25
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pa', 15, 'Doğru'), ('Pa', 16, 'Doğru'), ('Pa', 22, 'Doğru'),
('Pa', 24, 'Doğru'), ('Pa', 27, 'Doğru'), ('Pa', 35, 'Doğru'),
('Pa', 110, 'Doğru'), ('Pa', 121, 'Doğru'), ('Pa', 123, 'Doğru'),
('Pa', 127, 'Doğru'), ('Pa', 151, 'Doğru'), ('Pa', 157, 'Doğru'),
('Pa', 158, 'Doğru'), ('Pa', 202, 'Doğru'), ('Pa', 275, 'Doğru'),
('Pa', 284, 'Doğru'), ('Pa', 291, 'Doğru'), ('Pa', 293, 'Doğru'),
('Pa', 299, 'Doğru'), ('Pa', 305, 'Doğru'), ('Pa', 317, 'Doğru'),
('Pa', 338, 'Doğru'), ('Pa', 341, 'Doğru'), ('Pa', 364, 'Doğru'),
('Pa', 365, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Pa Scale Yanlış 15
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pa', 93, 'Yanlış'), ('Pa', 107, 'Yanlış'), ('Pa', 109, 'Yanlış'),
('Pa', 111, 'Yanlış'), ('Pa', 117, 'Yanlış'), ('Pa', 124, 'Yanlış'),
('Pa', 268, 'Yanlış'), ('Pa', 281, 'Yanlış'), ('Pa', 294, 'Yanlış'),
('Pa', 313, 'Yanlış'), ('Pa', 316, 'Yanlış'), ('Pa', 319, 'Yanlış'),
('Pa', 327, 'Yanlış'), ('Pa', 347, 'Yanlış'), ('Pa', 348, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Pt Scale (Psikasteni)
-- Pt Scale Doğru 39
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pt', 10, 'Doğru'), ('Pt', 15, 'Doğru'), ('Pt', 22, 'Doğru'),
('Pt', 32, 'Doğru'), ('Pt', 41, 'Doğru'), ('Pt', 67, 'Doğru'),
('Pt', 76, 'Doğru'), ('Pt', 86, 'Doğru'), ('Pt', 94, 'Doğru'),
('Pt', 102, 'Doğru'), ('Pt', 106, 'Doğru'), ('Pt', 142, 'Doğru'),
('Pt', 159, 'Doğru'), ('Pt', 182, 'Doğru'), ('Pt', 189, 'Doğru'),
('Pt', 217, 'Doğru'), ('Pt', 238, 'Doğru'), ('Pt', 266, 'Doğru'),
('Pt', 301, 'Doğru'), ('Pt', 304, 'Doğru'), ('Pt', 305, 'Doğru'),
('Pt', 317, 'Doğru'), ('Pt', 321, 'Doğru'), ('Pt', 336, 'Doğru'),
('Pt', 337, 'Doğru'), ('Pt', 340, 'Doğru'), ('Pt', 342, 'Doğru'),
('Pt', 343, 'Doğru'), ('Pt', 344, 'Doğru'), ('Pt', 346, 'Doğru'),
('Pt', 349, 'Doğru'), ('Pt', 351, 'Doğru'), ('Pt', 352, 'Doğru'),
('Pt', 356, 'Doğru'), ('Pt', 357, 'Doğru'), ('Pt', 358, 'Doğru'),
('Pt', 359, 'Doğru'), ('Pt', 360, 'Doğru'), ('Pt', 361, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Pt Scale Yanlış 9
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Pt', 3, 'Yanlış'), ('Pt', 8, 'Yanlış'), ('Pt', 36, 'Yanlış'),
('Pt', 122, 'Yanlış'), ('Pt', 152, 'Yanlış'), ('Pt', 164, 'Yanlış'),
('Pt', 178, 'Yanlış'), ('Pt', 329, 'Yanlış'), ('Pt', 353, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Sc Scale (Şizofreni)
-- Sc Scale Doğru 59
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Sc', 15, 'Doğru'), ('Sc', 16, 'Doğru'), ('Sc', 21, 'Doğru'),
('Sc', 22, 'Doğru'), ('Sc', 24, 'Doğru'), ('Sc', 32, 'Doğru'),
('Sc', 33, 'Doğru'), ('Sc', 35, 'Doğru'), ('Sc', 38, 'Doğru'),
('Sc', 40, 'Doğru'), ('Sc', 41, 'Doğru'), ('Sc', 47, 'Doğru'),
('Sc', 52, 'Doğru'), ('Sc', 76, 'Doğru'), ('Sc', 97, 'Doğru'),
('Sc', 104, 'Doğru'), ('Sc', 121, 'Doğru'), ('Sc', 156, 'Doğru'),
('Sc', 157, 'Doğru'), ('Sc', 159, 'Doğru'), ('Sc', 168, 'Doğru'),
('Sc', 179, 'Doğru'), ('Sc', 182, 'Doğru'), ('Sc', 194, 'Doğru'),
('Sc', 202, 'Doğru'), ('Sc', 210, 'Doğru'), ('Sc', 212, 'Doğru'),
('Sc', 238, 'Doğru'), ('Sc', 241, 'Doğru'), ('Sc', 251, 'Doğru'),
('Sc', 259, 'Doğru'), ('Sc', 266, 'Doğru'), ('Sc', 273, 'Doğru'),
('Sc', 282, 'Doğru'), ('Sc', 291, 'Doğru'), ('Sc', 297, 'Doğru'),
('Sc', 301, 'Doğru'), ('Sc', 303, 'Doğru'), ('Sc', 305, 'Doğru'),
('Sc', 307, 'Doğru'), ('Sc', 312, 'Doğru'), ('Sc', 320, 'Doğru'),
('Sc', 324, 'Doğru'), ('Sc', 325, 'Doğru'), ('Sc', 332, 'Doğru'),
('Sc', 334, 'Doğru'), ('Sc', 335, 'Doğru'), ('Sc', 339, 'Doğru'),
('Sc', 341, 'Doğru'), ('Sc', 345, 'Doğru'), ('Sc', 349, 'Doğru'),
('Sc', 350, 'Doğru'), ('Sc', 352, 'Doğru'), ('Sc', 354, 'Doğru'),
('Sc', 355, 'Doğru'), ('Sc', 356, 'Doğru'), ('Sc', 360, 'Doğru'),
('Sc', 363, 'Doğru'), ('Sc', 364, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Sc Scale Yanlış 19
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Sc', 8, 'Yanlış'), ('Sc', 17, 'Yanlış'), ('Sc', 20, 'Yanlış'),
('Sc', 37, 'Yanlış'), ('Sc', 65, 'Yanlış'), ('Sc', 103, 'Yanlış'),
('Sc', 119, 'Yanlış'), ('Sc', 177, 'Yanlış'), ('Sc', 178, 'Yanlış'),
('Sc', 187, 'Yanlış'), ('Sc', 192, 'Yanlış'), ('Sc', 196, 'Yanlış'),
('Sc', 220, 'Yanlış'), ('Sc', 276, 'Yanlış'), ('Sc', 281, 'Yanlış'),
('Sc', 306, 'Yanlış'), ('Sc', 309, 'Yanlış'), ('Sc', 322, 'Yanlış'),
('Sc', 330, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Ma Scale (Hipomani)
-- Ma Scale Doğru 35
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Ma', 11, 'Doğru'), ('Ma', 13, 'Doğru'), ('Ma', 21, 'Doğru'),
('Ma', 22, 'Doğru'), ('Ma', 59, 'Doğru'), ('Ma', 64, 'Doğru'),
('Ma', 73, 'Doğru'), ('Ma', 97, 'Doğru'), ('Ma', 100, 'Doğru'),
('Ma', 109, 'Doğru'), ('Ma', 127, 'Doğru'), ('Ma', 134, 'Doğru'),
('Ma', 143, 'Doğru'), ('Ma', 156, 'Doğru'), ('Ma', 157, 'Doğru'),
('Ma', 167, 'Doğru'), ('Ma', 181, 'Doğru'), ('Ma', 194, 'Doğru'),
('Ma', 212, 'Doğru'), ('Ma', 222, 'Doğru'), ('Ma', 226, 'Doğru'),
('Ma', 228, 'Doğru'), ('Ma', 232, 'Doğru'), ('Ma', 233, 'Doğru'),
('Ma', 238, 'Doğru'), ('Ma', 240, 'Doğru'), ('Ma', 250, 'Doğru'),
('Ma', 251, 'Doğru'), ('Ma', 263, 'Doğru'), ('Ma', 266, 'Doğru'),
('Ma', 268, 'Doğru'), ('Ma', 271, 'Doğru'), ('Ma', 277, 'Doğru'),
('Ma', 279, 'Doğru'), ('Ma', 298, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Ma Scale Yanlış 11
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Ma', 101, 'Yanlış'), ('Ma', 105, 'Yanlış'), ('Ma', 111, 'Yanlış'),
('Ma', 119, 'Yanlış'), ('Ma', 120, 'Yanlış'), ('Ma', 148, 'Yanlış'),
('Ma', 166, 'Yanlış'), ('Ma', 171, 'Yanlış'), ('Ma', 180, 'Yanlış'),
('Ma', 267, 'Yanlış'), ('Ma', 289, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Si Scale (Sosyal İçedönüklük)
-- Si Scale Doğru 34
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Si', 32, 'Doğru'), ('Si', 67, 'Doğru'), ('Si', 82, 'Doğru'),
('Si', 111, 'Doğru'), ('Si', 117, 'Doğru'), ('Si', 124, 'Doğru'),
('Si', 138, 'Doğru'), ('Si', 147, 'Doğru'), ('Si', 171, 'Doğru'),
('Si', 172, 'Doğru'), ('Si', 180, 'Doğru'), ('Si', 201, 'Doğru'),
('Si', 236, 'Doğru'), ('Si', 267, 'Doğru'), ('Si', 278, 'Doğru'),
('Si', 292, 'Doğru'), ('Si', 304, 'Doğru'), ('Si', 316, 'Doğru'),
('Si', 321, 'Doğru'), ('Si', 332, 'Doğru'), ('Si', 336, 'Doğru'),
('Si', 342, 'Doğru'), ('Si', 357, 'Doğru'), ('Si', 377, 'Doğru'),
('Si', 383, 'Doğru'), ('Si', 398, 'Doğru'), ('Si', 411, 'Doğru'),
('Si', 427, 'Doğru'), ('Si', 436, 'Doğru'), ('Si', 455, 'Doğru'),
('Si', 473, 'Doğru'), ('Si', 487, 'Doğru'), ('Si', 549, 'Doğru'),
('Si', 564, 'Doğru')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- Si Scale Yanlış 36
INSERT INTO scoring_keys (scale_name, question_number, scoring_answer) VALUES
('Si', 25, 'Yanlış'), ('Si', 33, 'Yanlış'), ('Si', 57, 'Yanlış'),
('Si', 91, 'Yanlış'), ('Si', 99, 'Yanlış'), ('Si', 119, 'Yanlış'),
('Si', 126, 'Yanlış'), ('Si', 143, 'Yanlış'), ('Si', 193, 'Yanlış'),
('Si', 208, 'Yanlış'), ('Si', 229, 'Yanlış'), ('Si', 231, 'Yanlış'),
('Si', 254, 'Yanlış'), ('Si', 262, 'Yanlış'), ('Si', 281, 'Yanlış'),
('Si', 296, 'Yanlış'), ('Si', 309, 'Yanlış'), ('Si', 353, 'Yanlış'),
('Si', 359, 'Yanlış'), ('Si', 371, 'Yanlış'), ('Si', 391, 'Yanlış'),
('Si', 400, 'Yanlış'), ('Si', 415, 'Yanlış'), ('Si', 440, 'Yanlış'),
('Si', 446, 'Yanlış'), ('Si', 449, 'Yanlış'), ('Si', 450, 'Yanlış'),
('Si', 451, 'Yanlış'), ('Si', 462, 'Yanlış'), ('Si', 469, 'Yanlış'),
('Si', 479, 'Yanlış'), ('Si', 481, 'Yanlış'), ('Si', 482, 'Yanlış'),
('Si', 505, 'Yanlış'), ('Si', 521, 'Yanlış'), ('Si', 547, 'Yanlış')
ON CONFLICT (scale_name, question_number) DO NOTHING;

-- ============================================================
-- 3. T-SCORE PARAMS
-- Source: dokumanlar/t_score_params_query.sql
-- ============================================================
INSERT INTO t_score_params (scale_name, gender, mean_m, sd, k_correction)
VALUES
('L',  'male',   6.45, 2.74, 0.00),
('F',  'male',   8.30, 4.62, 0.00),
('K',  'male',  13.98, 4.65, 0.00),
('Hs', 'male',  13.19, 4.07, 0.50),
('D',  'male',  20.63, 4.76, 0.00),
('Hy', 'male',  19.31, 4.71, 0.00),
('Pd', 'male',  22.22, 4.45, 0.40),
('Mf', 'male',  29.21, 3.82, 0.00),
('Pa', 'male',  11.12, 4.03, 0.00),
('Pt', 'male',  27.90, 6.30, 1.00),
('Sc', 'male',  29.82, 9.05, 1.00),
('Ma', 'male',  19.96, 4.40, 0.20),
('Si', 'male',  25.86, 7.97, 0.00),
('L',  'female',  6.00, 2.25, 0.00),
('F',  'female',  9.38, 5.16, 0.00),
('K',  'female', 11.82, 3.80, 0.00),
('Hs', 'female', 15.89, 4.88, 0.50),
('D',  'female', 23.86, 5.08, 0.00),
('Hy', 'female', 18.12, 5.31, 0.00),
('Pd', 'female', 22.84, 4.51, 0.40),
('Mf', 'female', 32.98, 3.67, 0.00),
('Pa', 'female', 11.93, 4.17, 0.00),
('Pt', 'female', 29.20, 6.59, 1.00),
('Sc', 'female', 31.06, 8.20, 1.00),
('Ma', 'female', 19.72, 4.36, 0.20),
('Si', 'female', 29.88, 7.52, 0.00)
ON CONFLICT (test_version, locale, age_group, scale_name, gender)
DO UPDATE SET mean_m = EXCLUDED.mean_m, sd = EXCLUDED.sd, k_correction = EXCLUDED.k_correction;

-- ============================================================
-- 4. MMPI INTERPRETATIONS
-- Source: belgeler/mmpi_interpretations_insert.sql
-- ============================================================
INSERT INTO mmpi_interpretations (scale_name, min_t_score, max_t_score, description, category) VALUES
('L', 69, 100, 'Kişi sosyal açıdan kabul gören yanıtlar vererek kendini kontrol eden, etkili biri olduğu izlenimi bırakmaya çalışıyor olabilir. Güvenilmez, pasif, uzak duran, kaygılı, içe kapanık bir yapıya sahip olabilir. Değerleriyle ilişki kurmaları zor olabilir. Duruma özgü tepkileri yavaş olduğu düşünülebilir.', 'validity'),
('L', 64, 68, 'Kişi maddeleri gelişi güzel doldurmuş olabilir. Kişi kendindeki zayıflıkları inkar ediyor olabilir. Kişi patolojik olarak kendinde ki iyi ve ahlaki inanç ve eğilimleri nedeniyle kendine aşırı kontrol koyabilir. Ufak hatalarını bile inkar etme eğiliminde olabilir.', 'validity'),
('L', 59, 63, 'Kişi iyi görünme çabası içerisinde olduğu düşünülebilir. Kişide sosyal açıdan kabul gören yanıtlar verme eğilimi olabilir. Kişinin aşırı geleneksel ve sosyal açıdan uyumlu olduğu düşünülebilir.', 'validity'),
('L', 36, 58, 'Bu aralığa ilişkin özgün bir durum tanımlanmamıştır.', 'validity'),
('L', 0, 35, 'Bağımsız, kendine güvenen, ufak sosyal hatalarını kabul etmeye hazır bir yapısı olabilir.', 'validity'),
('F', 70, 100, 'Geçersiz profil - Test sonuçları güvenilir değildir.', 'validity'),
('F', 55, 69, 'Kişi negativist, değişken, huysuz ve huzursuz olabilir. Durumsal stresi olduğu düşünülebilir.', 'validity'),
('F', 44, 54, 'Kişi sadece belirgin maddelere yanıt vermiş olabilir. Kişinin ilgi alanlarının daraldığı düşünülebilir. Kişi psikopatolojiyi, duygusal gerginliği gizliyor olabilir, direnç sahibi olabilir.', 'validity'),
('F', 0, 43, 'Kişi herhangi bir psikopatoloji, gerginlik ya da stresi olmadığını görünümünü vermek istiyor olabilir.', 'validity'),
('K', 72, 100, 'Kişi savunucu olabilir. Kendinde psikolojik sorunlar olduğunu kabul etmeyebilir. Kati ve esnek olabilir. Kendisindeki sorunu kabul etmek istemeyebilir. Tedaviye yanıtının kötü olduğu düşünülebilir.', 'validity'),
('K', 61, 71, 'Kişi kendisindeki ve çevresindeki bozuklukları en aza indirgeme ve görmezden gelme eğiliminde olabilir. İç görüsü az olabilir ve savunmaları artmış olabilir.', 'validity'),
('K', 46, 60, 'Kişinin dengeli bir yapısı olabilir. Kişinin ego gücü iyi, olumlu kendilik değerine ve uyuma işaret edebilir.', 'validity'),
('K', 27, 45, 'Kişinin zayıf kendilik değeri olabilir. Kişi kendinden hiç memnun olmayabilir.', 'validity'),
('K', 0, 26, 'Kişinin çok zayıf kendilik değeri olabilir. Kişi ciddi uyum sorunları yaşayabilir.', 'validity'),
('Hs', 75, 84, 'Kişi bedensel yakinalar ile çok fazla uğraşabilir. İş yapma isteği azalmış, yakinalarini sürekli araştırabilir. Benmerkezci ve narsist olabilir.', 'clinical'),
('Hs', 60, 74, 'Kişi fiziksel bozukluk göstermiş olabilir. Sağlık konularına aşırı duyarlı olabilir. Kötümser ve yaşamını sıkıcı hale getirme eğiliminde olabilir.', 'clinical'),
('Hs', 50, 59, 'Kişi yetenekli, sorumluluk sahibi, vicdanli, dikkatli ve yargılamalari iyi bir yapiya sahip olabilir.', 'clinical'),
('Hs', 21, 49, 'Kişi hastalığın hiç konu olmadığı ailelerde yetişmiş olabilir. Uyanık, iyimser, yeterli ve yaşamda etkin kişiler olabilir.', 'clinical'),
('D', 70, 79, 'Kişi ciddi ve kendine güveni olmayan bir yapiya sahip olabilir. Belirgin depresyonu olabilir.', 'clinical'),
('D', 60, 69, 'Kişide orta duzey depresyon gorulebilir. Endişe ve karamsarlik gostergesi olabilir.', 'clinical'),
('D', 45, 59, 'Kişi yaşaminda iyimserlik ve karamsarlik dengesini kurmus olabilir.', 'clinical'),
('D', 28, 44, 'Kişi neseli, merakli, iyimser, aktif ve disa donuk bir yapiya sahip olabilir.', 'clinical'),
('Hy', 70, 75, 'Kişi bastirma ve inkar kullanabilir, itaat eden, saf ve cocukca benmerkezci olabilir.', 'clinical'),
('Hy', 60, 69, 'Histerik ozellikler belirgin olabilir. Kişi kendine odaklanmis olabilir, ic goru azligi olabilir.', 'clinical'),
('Hy', 45, 59, 'Bu alana ozgu bir tanimlama yoktur.', 'clinical'),
('Hy', 24, 44, 'Kişi kendisini surekli elestirebilir. Olumlu Kişiler arasi iliskileri inkar etme egilimi olabilir.', 'clinical'),
('Pd', 70, 100, 'Kişi antisosyal davranislar sergileyebilir. Durtu kontrol sorunlari olabilir.', 'clinical'),
('Pd', 60, 69, 'Kişi risk alabilen, enerjik, sosyal, maceraperest ve atilgan olabilir.', 'clinical'),
('Pd', 45, 59, 'Kişide aşırı kontrol koyma ve Kişitlama az olabilir. Sosyal kurallara kismen uyum olabilir.', 'clinical'),
('Pd', 20, 44, 'Kişi duragan, pasif ve atilgan olmayan bir yapiya sahip olabilir.', 'clinical'),
('Pa', 70, 100, 'Kişi paranoid dusunceler gelistirebilir, aşırı supheci olabilir.', 'clinical'),
('Pa', 60, 69, 'Kişi duyarlı bir yapiya sahip olabilir. Elestiri ve onerileri cok ciddiye alabilir.', 'clinical'),
('Pa', 55, 59, '55-59 T puani arasinda olan bireyler anlayisli, duyarlı Kişilerdir.', 'clinical'),
('Pa', 45, 54, 'Kişi digerlerini degerlendirmede esnek olabilir.', 'clinical'),
('Pa', 27, 44, 'Kişinin digerlerine duyarlıgi olmayabilir. Geleneksel ve ilkel bir yapisi olabilir.', 'clinical'),
('Pt', 75, 84, 'Temiz, titiz, duzenli. Onemsiz sorunlar karsisinda gerginlik ve endise yasayabilir.', 'clinical'),
('Pt', 60, 74, 'Kişi mukemmeliyetci, titiz ve kendini elestiren bir yapiya sahip olabilir.', 'clinical'),
('Pt', 45, 59, 'Kişi islerini ve yasamini endise ve guvensizlik duymadan yurutebilir.', 'clinical'),
('Pt', 20, 44, 'Rahat, duygusal, gerginligi olmayan. Kendine guvenebilir ve uyumlu olabilir.', 'clinical'),
('Sc', 60, 74, 'Profil tumu ele alinmalidir. Soyut konularla ilgileniyor olabilir.', 'clinical'),
('Sc', 45, 59, 'Kişi kurumsal ve pratik goruslerini normal bicimde birlestirebiliyor olabilir.', 'clinical'),
('Sc', 21, 44, 'Pratik bir yapisi olabilir. Uyumlu, sorumlu, bagimli ve temkinli olabilir.', 'clinical'),
('Ma', 70, 100, 'Kişi enerjik, disa donuk, aktif. Onay ve status kazanmak icin caba harcayabilir.', 'clinical'),
('Ma', 60, 69, 'Kişi hos, enerjik, merakli, sosyal. Iyimserlik, bagimsizlik ve kendine guven.', 'clinical'),
('Ma', 45, 59, 'Normal araligi.', 'clinical'),
('Ma', 21, 44, 'Dusuk enerji duzeyi, gudu azligi olabilir. 45 yas ustunde beklenen bir durumdur.', 'clinical'),
('Si', 70, 100, 'Kişi sosyal acidan beceriksiz olabilir, iliski kurmaktan kacinabilir.', 'clinical'),
('Si', 60, 69, 'Kişi kendini ortaya koymak istemeyebilir. Cekingen utangac olabilir.', 'clinical'),
('Si', 45, 59, 'Kişi sosyal iliski kurma konusunda basarili olabilir.', 'clinical'),
('Si', 25, 44, 'Iyimser, manipulative, yuzeysel. Durtu kontrol sorunlari olabilir.', 'clinical')
ON CONFLICT DO NOTHING;

-- Mf scale with gender
INSERT INTO mmpi_interpretations (scale_name, min_t_score, max_t_score, description, category, gender) VALUES
('Mf', 80, 100, 'Erkeklerde kulturel erkeksi rolle ozdesim olmadigini gosterir. Pasif erkeklere isaret eder.', 'clinical', 'male'),
('Mf', 41, 79, 'Erkeklerde orta duzey feminen ozellikler. Sanatsal ve estetik ilgiler.', 'clinical', 'male'),
('Mf', 26, 40, 'Maskulen gorunmek icin kompulsif ugras. Altta yatan kendine guvensizlik.', 'clinical', 'male'),
('Mf', 65, 100, 'Kadinlar guclu, saldirgan, yonlendirici ve yarisamcidir. Bagimsiz ve kendine guvenli.', 'clinical', 'female'),
('Mf', 41, 55, 'Kadinlarin ilgi alanlari orta sinif kadinlarinin ilgilendikleri konular ile olabilir.', 'clinical', 'female'),
('Mf', 26, 40, 'Kadinlar pasif, cekingen. Mf dusuklugu nevrotik uclude yukselme ile iliskilidir.', 'clinical', 'female')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 5.  TEXT
-- Source: dokumanlar/create_settings_table.sql
-- ============================================================
INSERT INTO kvkk (id, kvkk_title, kvkk_text, kvkk_required) VALUES (
    1,
    'KVKK Aydinlatma Metni',
    '<h4 class=\"text-center mb-4\">MİNNESOTA ÇOK YÖNLÜ KİŞİLİK ENVANTERİ (MMPI) TESTİ</h4>\n<h5 class=\"text-center mb-4\">KİŞİSEL VERİLERİN KORUNMASI KANUNU HAKKINDA AÇIKLAMALAR VE MUVAFAKATNAME</h5>\n\n<h6><strong>1. BİLGİLENDİRME</strong></h6>\n<p>MMPI Testinin açılımı Minnesota Çok Yönlü Kişilik Envanteri. Bu test bireyin kişisel ve toplumsal uyumunu objektif olarak değerlendirmeyi amaçlayan bir testtir.</p>\n\n<h6><strong>Veri Sorumlusu</strong></h6>\n<p>6638 sayılı Kişisel Verilerin Korunması Kanunu (\"6698 sayılı Kanun\") uyarınca, kişisel verileriniz; veri sorumlusu olarak OGULTURK AŞ (\"ŞİRKET\") tarafından aşağıda açıklanan kapsamda toplanacak, işlenebilecek ve ilgili birim sorumlusu ile paylaşılacaktır.</p>\n<p>Şirketimiz, katılımcılara ilişkin kişisel veriler bakımından 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında \"veri sorumlusu\" sıfatına sahip olup işbu Aydınlatma Metni ile söz konusu Kanun uyarınca katılımcıların Şirket tarafından gerçekleştirilen kişisel veri işleme faaliyetleri hakkında aydınlatılması hedeflenmektedir.</p>\n\n<h6><strong>İşlemenin Amacı</strong></h6>\n<p>MMPI kişilik testi, bu alanda kişiliği tespitte kullanılacak en güvenilir ve geçerli olma özelliğine sahiptir. Bu kapsamda ve güvenirlik düzeyinde ülkemizde uygulanan başka bir test mevcut değildir. MMP kişilik testi dünyanın tek ve en güvenilir bilimsel kişilik testidir, kişiyi objektif ve derinlemesine tanımasını sağlar, psikolojik yetkinliğinizi tespit eder, işe en uygun personeli en güvenilir şekilde seçmenize olanak tanır.</p>\n<p>Yüksek öneme sahip ve üst düzey kamu görevlilerinin seçimi, polis memuru alımları ve birim değişikliklerinde yapılacak seçimler, silah taşma yetkisi verilmiş kişilerde, koruma ve danışmanlar, cezai ve hukuki ehliyetin olup olmadığına yönelik tespit yapılacak kişiler ve adli yargı adaylarını değerlendirme ve seçme işlemlerinde kullanılır.</p>\n<p>Bu kapsamda \"Minnesota Çok Yönlü Kişilik Envanteri\" başlıklı test, uygulayıcı belgesi alan psikolog tarafından uygulanması, sonuçlarının standart MMPI değerlendirme programı ve gerektiğinde manuel olarak elle değerlendirilmesi gerekir. Araştırma sırasında elde edilecek bilgiler gizli tutulacak ve sadece riskleri önleme amaçlı kullanılacaktır.</p>\n\n<h6><strong>İşlemenin Hukuki Dayanağı</strong></h6>\n<p>Kişisel verileriniz/özel nitelikli kişisel verileriniz şirket çalışanlarının veya çalışan adaylarının doğru pozisyonlarda görevlendirilmesini sağlayabilmek için özgür iradenize dayanan açık rızanıza dayanılarak işlenecektir.</p>\n<ul>\n    <li>Psikolojik yetkinliğinizi tespit etmek,</li>\n    <li>İşe en uygun personeli seçmek,</li>\n    <li>Riskleri önlemek ve daha kaliteli hizmet sağlamak</li>\n</ul>\n\n<h6><strong>İşlenecek Kişisel Veriler ve Özel Nitelikli Kişisel Veriler</strong></h6>\n<p>İşbu Test ile;</p>\n<ul>\n    <li>Kimlik bilgisi,</li>\n    <li>İletişim bilgisi,</li>\n    <li>Ailevi bilgiler,</li>\n    <li>Sağlık bilgileri,</li>\n</ul>\n<p>gibi kategorilerde kişisel veri toplanabilmektedir.</p>\n\n<h6><strong>Kişisel Verileri Toplamanın ve İşlemenin Yöntemi</strong></h6>\n<p>Kişisel verileriniz MMPI test formları ile toplandıktan sonra kapalı zarf içinde tutulacaktır. Veriler psikolog tarafından MMPI programına işlenecektir. Analizler gerçekleştikten sonra sonuç raporları kapalı zarf içinde KVKK gereğince uygun şekilde saklanacaktır.</p>\n\n<h6><strong>Veri Sahiplerinin Kişisel Verilerinin Güvenliğinin Sağlanması İçin Alınan Tedbirler</strong></h6>\n<p>6698 Sayılı Kişisel Verileri Koruma Kanun\"un 12. maddesine uygun olarak, Şirket tarafından veri güvenliğinin sağlanması için,</p>\n<ul>\n    <li>Kişisel venlerin hukuka aykırı olarak işlenmesini önlemek,</li>\n    <li>Kişisel verilere hukuka aykırı olarak erişilmesini önlemek,</li>\n    <li>Kişisel verilerin muhafazasını sağlamak,</li>\n</ul>\n<p>Amacıyla lüzumlu olan güvenlik düzeyini temin etmeye yönelik gerekli her türlü teknik ve idari tedbirler alınmaktadır.</p>\n\n<h6><strong>Kişisel Verileriniz ile İlgili Haklarınız</strong></h6>\n<p>Kişisel veri sahipleri olarak, haklarınıza ilişkin taleplerinizi aşağıda düzenlenen yöntemlerle iletmeniz durumunda ŞİRKET talebin niteliğine göre talebi en kısa sürede ve en geç otuz gün içinde sonuçlandıracaktır. Bu kapsamda kişisel veri sahipleri;</p>\n<ul>\n    <li>Kişisel veri işlenip işlenmediğini öğrenme,</li>\n    <li>Kişisel verileri işlenmişse buna ilişkin bilgi talep etme,</li>\n    <li>Kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,</li>\n    <li>Yurt içinde kişisel verilerin aktarıldığı üçüncü kişileri bilme,</li>\n    <li>Kişisel verilerin eksik veya yanlış işlenmiş olması halinde bunların düzeltilmesini isteme,</li>\n    <li>Kişisel verilerin silinmesini veya yok edilmesini isteme,</li>\n    <li>İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme,</li>\n    <li>Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması halinde zararın giderilmesini talep etme haklarına sahiptir.</li>\n</ul>\n\n<p>Yukarıda belirtilen haklarınızı kullanma ile ilgili talebinizi, 6698 sayılı Kanunu\"nun 13. maddesinin 1. fıkrası ve 30356 sayılı ve 10.03.2018 tarihli Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ gereğince Türkçe ve yazılı olarak veya kayıtlı elektronik posta (KEP) adresi, güvenli elektronik imza, mobil imza ya da Şirket\"e daha önce bildirilen ve sistemimizde kayıtlı bulunan elektronik posta adresini kullanmak suretiyle iletebilirsiniz. Başvurularda sadece başvuru sahibi kişi hakkında bilgi verilecek olup diğer aile fertleri ve üçüncü kişiler hakkında bilgi alınması mümkün olmayacaktır. Şirket\"in cevap vermeden önce kimliğinizi doğrulama hakkı saklıdır.</p>\n\n<p>Başvurunuzda;</p>\n<ul>\n    <li>Adınızın, soyadınızın ve başvuru yazılı ise imzanızın,</li>\n    <li>Türkiye Cumhuriyeti vatandaşları için T.C. kimlik numaranızın, yabancı iseniz uyruğunuzun, pasaport numaranızın veya varsa kimlik numaranızın,</li>\n    <li>Tebligata esas yerleşim yeri veya iş yeri adresinizin,</li>\n    <li>Varsa bildirime esas elektronik posta adresi, telefon ve faks numaranızın,</li>\n    <li>Talep konunuzun,</li>\n</ul>\n<p>bulunması zorunlu olup varsa konuya ilişkin bilgi ve belgelerin de başvuruya eklenmesi gerekmektedir.</p>\n\n<h6><strong>Kişisel Verileriniz ile İlgili Başvurularınız</strong></h6>\n<p>Yazılı olarak yapmak istediğiniz başvurularınızı, gerekli belgeleri ekleyerek veri sorumlusu olarak Şirketimizin Yenice, Soğuksu Caddesi no:68, 06890 Kızılcahamam/ANKARA adresine verebilir, başvuru formuna Şirketimizin ilgili biriminden erişebilirsiniz.</p>\n<p>E-posta yoluyla yapmak istediğiniz başvurularınızı ogulturkselma@gmail.com adresine yapabilirsiniz.</p>\n\n<h6><strong>Araştırmayla İlgili Bilgiler:</strong></h6>\n<p><strong>Araştırmanın Nedeni:</strong> Riskleri önlemek ve daha kaliteli hizmet sağlamak.</p>\n<p><strong>Süresi:</strong> 60-90 dk</p>\n<p><strong>Araştırmanın Yürütüleceği Yer:</strong> İlgili Proje kvkk-calisan-bilgi adresinde yer alan OGULTURK A.Ş</p>\n\n<div class=\"alert alert-info mt-3\">\n    <p class=\"mb-0\"><strong>KİŞİSEL VERİLERİN KORUNMASI KANUNU HAKKINDA ÇALIŞAN BİLGİLENDİRME yazısını aldım, okudum ve anladım</strong></p>\n</div>\n\n<h6><strong>2. MUVAFAKATNAME</strong></h6>\n<p>OGULTURK A.Ş. MMPI Testi esnasında alınan 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında yer alan kişisel verilerimin/özel nitelikli kişisel verilerimin alınmasına, işlenmesine, aktarılmasına, silinmesine, anonim hale getirilmesine ve sair surette işlenmesine ve 2 yıl müddetle muhafaza edilmesine özgür irademle açık rızamla <strong>MUVAFAKAT EDİYORUM.</strong></p>',
    true
) ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- 6. PAGE CONTENT
-- Source: dokumanlar/create_page_content_table.sql
-- ============================================================
INSERT INTO page_content (id, page_key, page_title, page_subtitle, page_body) VALUES
(1,'gizlilik', 'Gizlilik Politikasi', 'Kişisel verilerinizin nasil toplandigi, islendigi ve korundugu hakkinda bilgi',
'<h4>1. Veri Sorumlusu</h4><p>6698 sayili Kişisel Verilerin Korunmasi Kanunu uyarinca, Kişisel verileriniz; veri sorumlusu olarak <strong>OGULTURK A.S.</strong> tarafindan toplanmakta, islenmekte ve ilgili birim sorumlusu ile paylasilmaktadir.</p>'),
(2,'kullanim', 'Kullanim Kosullari', 'MMPI psikolojik test sistemini kullanirken uymaniz gereken kurallar',
'<h4>1. Hizmetin Kapsami</h4><p>OGULTURK A.S. tarafindan sunulan MMPI psikolojik test sistemi, bireylerin Kişisel ve toplumsal uyumlarini objektif olarak degerlendirmeyi amaclayan bir dijital uygulamadir.</p>'),
(3,'hakkimizda', 'Hakkimizda', 'OGULTURK A.S. ve MMPI Psikolojik Degerlendirme Sistemi',
'<p>OGULTURK A.S. olarak, bireylerin Kişisel ve toplumsal uyumlarini objektif bir sekilde degerlendirmek amaciyla MMPI test hizmeti sunuyoruz.</p>')
ON CONFLICT (page_key) DO NOTHING;

-- ============================================================
-- 7. SETTINGS
-- ============================================================
INSERT INTO settings (setting_key, setting_value) VALUES
('test_version', 'MMPI'),
('max_dont_know', '10'),
('auto_save_interval', '30000'),
('app_name', 'MMPI Psikolojik Degerlendirme Sistemi')
ON CONFLICT (setting_key) DO NOTHING;

COMMIT;

-- ============================================================
-- Data imported successfully.
-- Next: psql -U mmpi_user -d mmpi_db -f 03_setup_admin.sql
-- ============================================================
