INSERT INTO questions (question_number, question_text, category_id) VALUES
(1, 'Teknik yazılardan hoşlanırım.', 1),
(2, 'İştahım iyidir.', 1),
(3, 'Çok defa sabahları dinç ve dinlenmiş olarak uyanırım.', 1),
(4, 'Kütüphaneci olarak çalışmayı seveceğimi sanıyorum.', 1),
(5, 'Gürültüden kolayca uyanırım.', 1),
(6, 'Cinayet haberlerini okumaktan hoşlanırım.', 1),
(7, 'Çoğu zaman el ve ayaklarımın sıcaklığı iyidir.', 1),
(8, 'Günlük hayatım beni ilgilendirecek şeylerle doludur.', 1),
(9, 'Bugün de hemen hemen eskisi kadar iyi çalışabiliyorum.', 1),
(10, 'Çoğu zaman boğazım tıkanır gibi olur.', 1),
(11, 'İnsan rüyalarını anlamaya çalışmalı ve kendini onlara göre ayarlamalıdır.', 1),
(12, 'Polis romanlarından ya da esrarengiz yazılardan hoşlanırım.', 1),
(13, 'Büyük bir sinir gerginliği içinde çalışırım.', 1),
(14, 'Ayda bir iki defa ishal olurum.', 1),
(15, 'Arasıra söylenemeyecek kadar ayıp şeyler düşünürüm.', 1),
(16, 'Hayatta kötülükler hep beni bulur.', 1),
(17, 'Babam iyi bir adamdır.', 2),
(18, 'Pek seyrek kabız olurum.', 1),
(19, 'Yeni bir işe girince kimin gözüne girmem gerektiğini öğrenmek isterim.', 1),
(20, 'Cinsel yaşamımdan memnunum.', 4),
(21, 'Zaman zaman evi bırakıp gitmek istemişimdir.', 1),
(22, 'Arasıra kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.', 1),
(23, 'Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.', 'Sağlık'),
(24, 'Kimse beni anlamıyor.', 1),
(25, 'Şarkıcı olmayı isterim.', 1),
(26, 'Başım derde girince susmayı tercih ederim.', 1),
(27, 'Bazen kötü ruhların beni etkileri altına aldığını hissederim.', 1),
(28, 'Kötülüğe kötülükle karşılık vermek prensibimdir.', 1),
(29, 'Çoğu kez midem ekşir.', 'Sağlık'),
(30, 'Bazen canım küfretmek ister.', 1),
(31, 'Sık sık geceleri kabus geçiririm.', 1),
(32, 'Zihnimi bir iş üzerinde toplamada güçlük çekerim.', 1),
(33, 'Başımdan çok garip ve tuhaf şeyler geçti.', 1),
(34, 'Çoğu zaman öksürüğüm vardır.', 1),
(35, 'Başkaları engel olmasaydı daha çok başarılı olurdum.', 1),
(36, 'Sağlığım beni pek kaygılandırmaz.', 'Sağlık'),
(37, 'Cinsel yaşamım yüzünden başım hiç derde girmedi.', 4),
(38, 'Gençliğimde bir devre ufak tefek şeyler çaldım.', 1),
(39, 'Bazen içimde bir şeyler kırmak isteği geçer.', 1),
(40, 'Başka bir şey yapmaktansa çoğu zaman oturup hayal kurmayı severim.', 1),
(41, 'Kendimi toparlayamadığım için günler, haftalar hatta aylarca hiç bir şeye el sürmediğim olur.', 1),
(42, 'Ailem seçtiğim (veya seçmek istediğim) mesleği beğenmiyor.', 2),
(43, 'Kuşkulu ve rahatsız uyurum.', 1),
(44, 'Çoğu zaman başımın her tarafı ağrır.', 'Sağlık'),
(45, 'Her zaman doğruyu söylemem.', 1),
(46, 'Şimdi her zamankinden daha iyi düşünüp tartabiliyorum.', 1),
(47, 'Ortada hiç bir neden yokken haftada bir ya da daha sık birdenbire her yanımı ateş basar.', 1),
(48, 'Başkaları ile bir arada iken kulağıma çok garip şeyler gelmesinden rahatsız olurum.', 1),
(49, 'Kanunların hemen hepsi kaldırılırsa daha iyi olur.', 1),
(50, 'Bazen ruhum vücudumdan ayrılır.', 1),
(51, 'Sağlığım birçok arkadaşımınki kadar iyidir.', 'Sağlık'),
(52, 'Uzun zamandan beri görmediğim okul arkadaşlarım ya da tanıdıklarım önce benimle konuşmazlarsa onları görmemezlikten gelmeyi tercih ederim.', 6),
(53, 'Hocaların dua okuyup üflemesi hastalığı iyileştirir.', 1),
(54, 'Tanıdıklarımın çoğu beni sever.', 1),
(55, 'Kalp ve göğüs ağrılarından hemen hemen hiç şikayetim yoktur.', 'Sağlık'),
(56, 'Çocukken okuldan kaçtığım için bir iki defa cezalandırıldım.', 1),
(57, 'İnsanlarla çabucak kaynaşırım.', 1),
(58, 'Kur’an’ın buyurdukları bir bir çıkmaktadır.', 1),
(59, 'Çok defa benden az bilenlerden emir alarak çalışmak zorunda kaldım.', 1),
(60, 'Her gün gazetelerin baş yazılarını okumam.', 1),
(61, 'Gerektiği gibi bir hayat yaşayamadım.', 1),
(62, 'Vücudumun bazı yerlerinde çok defa yanma, gıdıklanma, karıncalanma veya uyuşukluk hissederim.', 1),
(63, 'Büyük abdest yapmada ya da tutmada hiç bir güçlük çekmem.', 'Sağlık'),
(64, 'Bazen başkalarının sabrını tüketecek kadar bir şeye saplanıp kalırım.', 1),
(65, 'Babamı severim.', 2),
(66, 'Etrafımda başkalarının görmedikleri eşya ve hayvanlar ya da insanlar görürüm.', 1),
(67, 'Başkalarının mutlu göründüğü kadar mutlu olmayı isterdim.', 5),
(68, 'Ensemde nadiren ağrı hissederim.', 'Sağlık'),
(69, 'Kendi cinsimden olanları oldukça çekici bulurum.', 4),
(70, 'Körebe oyunundan hoşlanırdım.', 1),
(71, 'Birçok kimseler başkalarının ilgi ve yardımlarını sağlamak için talihsizliklerini abartırlar.', 1),
(72, 'Hemen hemen her gün mide ağrılarından rahatsız olurum.', 'Sağlık'),
(73, 'Ben önemli bir kimseyim.', 1),
(74, 'Çoğu zaman kız olmayı isterdim. (Şayet kız iseniz) Kız olduğuma hiç üzülmedim.', 1),
(75, 'Arasıra öfkelenirim.', 1),
(76, 'Çoğu zaman kendimi hüzünlü hissederim.', 5),
(77, 'Aşk romanları okumaktan hoşlanırım.', 1),
(78, 'Şiiri severim.', 1),
(79, 'Kolay incinmem.', 1),
(80, 'Bazen hayvanlara rahat vermem.', 1),
(81, 'Orman bekçiliği gibi işlerden hoşlanacağımı sanıyorum.', 1),
(82, 'Tartışmalarda çabucak yenilirim.', 1),
(83, 'Çok çalışabilen ya da çalışmak isteyen kişinin başarılı olma şansı yüksektir.', 1),
(84, 'Bugünlerde artık hiç ilerleme umudum kalmamış gibi hissediyorum.', 5),
(85, 'Kullanamayacak bile olsam bazen başkalarının ayakkabı, eldiven vb. gibi özel eşyaları o kadar hoşuma gider ki dokunmak ve aşırmak isterim.', 1),
(86, 'Kendime hiç güvenim yoktur.', 5),
(87, 'Çiçek satıcısı olmayı isterdim.', 1),
(88, 'Genel olarak hayatın yaşanmaya değer olduğu kanısındayım.', 1),
(89, 'İnsanlara gerçeği kabul ettirmek güçtür.', 1),
(90, 'Bugün yapmam gereken işleri ara sıra yarına bıraktığım olur.', 1),
(91, 'Benimle alay edilmesine aldırmam.', 1),
(92, 'Hemşire olmayı isterdim.', 1),
(93, 'Yükselmek için birçok kimse yalan söylemekten çekinmez.', 1),
(94, 'Sonradan pişman olacağım pek çok şeyi yaptığım olur.', 1),
(95, 'Namazımı hemen hemen muntazaman kılarım.', 1),
(96, 'Ailemle pek az kavga ederim.', 2),
(97, 'Bazen zararlı ya da çok kötü işler yapmak için içimde çok güçlü bir istek duyarım.', 1),
(98, 'Kıyamet gününe inanıyorum.', 1),
(99, 'Gürültülü eğlencelere katılmaktan hoşlanırım.', 1),
(100, 'Bildiğim bir konuda bir kimse saçma sapan ya da cahilce konuşursa onu hemen düzeltirim.', 1),
(101, 'Bence cinsel yönden kadınlar da erkekler kadar serbest olmalıdır.', 4),
(102, 'En büyük mücadelelerimi kendimle yaparım.', 1),
(103, 'Vücudumda pek az seyirme ve kasılma olur.', 'Sağlık'),
(104, 'Başıma ne gelirse gelsin aldırış etmiyorum.', 1),
(105, 'Keyfim yerinde olmadığı zaman tersliğim üzerimdedir.', 1),
(106, 'Çoğu zaman büyük bir hata ya da kötülük yaptığım duygusuna kapılırım.', 1),
(107, 'Çoğu zaman mutluyumdur.', 5),
(108, 'Çoğu zaman bana, kafam şişmiş ya da burnum tıkanmış gibi gelir.', 'Sağlık'),
(109, 'Bazı kimseler o kadar amirane davranırlar ki haklı bile olsalar içimden dediklerinin aksini yapmak gelir.', 1),
(110, 'Bana kötülük etmek isteyen biri var.', 1),
(111, 'Sırf heyecanlanmak için tehlikeli bir işe girişmedim.', 1),
(112, 'Doğru bildiğim şeyler için çoğu zaman direnmek zorunda kalırım.', 1),
(113, 'Kanunların uygulanması gerektiğine inanırım.', 1),
(114, 'Çoğu zaman başım sıkı bir çember içindeymiş gibi hissederim.', 'Sağlık'),
(115, 'Ahirete inanırım.', 1),
(116, 'Bahse girdiğim yarış ya da oyunlardan daha çok zevk alırım.', 1),
(117, 'Birçok kimseler daha çok yakalanmaktan korktukları için dürüsttürler.', 1),
(118, 'Dersten kaçtığım için ara sıra müdüre gönderildiğim oldu.', 1),
(119, 'Konuşma tarzım her zamanki gibidir.', 1),
(120, 'Evde sofra adabına dışarıdaki kadar dikkat etmem.', 1),
(121, 'Aleyhimde bazı tertipler kurulduğuna inanıyorum.', 1),
(122, 'Tanıdığım insanların çoğu kadar becerikli ve zeki olduğumu sanıyorum.', 1),
(123, 'Beni takip edenler olduğuna inanıyorum.', 1),
(124, 'Birçokları kaybetmektense çıkarlarını korumak için pek doğru olmayan yollara başvururlar.', 1),
(125, 'Midemden oldukça rahatsızım.', 'Sağlık'),
(126, 'Tiyatrodan hoşlanırım.', 1),
(127, 'Dertlerimin çoğundan kimin sorumlu olduğunu biliyorum.', 1),
(128, 'Kan görünce korkmam ya da fenalaşmam.', 5),
(129, 'Bazen ters ve suratsız olurum.', 1),
(130, 'Hiçbir zaman kan kusmadım ya da kan tükürmedim.', 'Sağlık'),
(131, 'Hastalığa yakalanacağım diye kaygılanmam.', 'Sağlık'),
(132, 'Çiçek koleksiyonu yapmayı ve evde çiçek yetiştirmeyi severim.', 1),
(133, 'Hiçbir zaman normal olmayan cinsel ilişkilere girişmedim.', 4),
(134, 'Bazen kafamdaki düşünceler o kadar hızlıdır ki söylemeyi yetiştiremem.', 1),
(135, 'Farkedilmeyeceğimden emin olsam sinemaya biletsiz girerdim.', 1),
(136, 'Bana iyilik yapan kimselerin genel olarak gizli bir amacı olabileceğini düşünürüm.', 1),
(137, 'Aile hayatımın tanıdığım kimselerin çoğununki kadar iyi olduğuna inanıyorum.', 2),
(138, 'Eleştiri beni çok kırar.', 1),
(139, 'Bazen sanki kendimi ya da başkasını incitmek zorundaymışım gibi hissederim.', 1),
(140, 'Yemek pişirmeyi severim.', 1),
(141, 'Davranışlarımı çoğu zaman etrafımdakilere göre ayarlarım.', 1),
(142, 'Bazen hiçbir işe yaramadığımı düşünürüm.', 5),
(143, 'Çocukken başlarına ne gelirse gelsin aralarındaki birliği koruyan bir gruptaydım.', 1),
(144, 'Asker olmak isterim.', 1),
(145, 'Bazen biriyle yumruk yumruğa kavgaya girişmek istediğim olur.', 1),
(146, 'Seyahat edip gezip tozmadıkça mutlu olamam.', 1),
(147, 'Çabuk karar vermediğim için çok fırsat kaçırdım.', 1),
(148, 'Önemli bir iş üzerinde çalışırken başkalarının işimi yarıda kesmeleri sabrımı taşırır.', 1),
(149, 'Hatıra defteri tutardım.', 1),
(150, 'Oyunda kaybetmektense kazanmayı isterim.', 1),
(151, 'Biri beni zehirlemeye çalışıyor.', 1),
(152, 'Çoğu geceler zihnimi hiçbir şey kurcalamadan uykuya dalarım.', 1),
(153, 'Son bir kaç yıl içinde sağlığım çoğu zaman iyi idi.', 'Sağlık'),
(154, 'Hiç sinir nöbeti ya da havale geçirmedim.', 'Sağlık'),
(155, 'Ne şişmanlıyorum ne de zayıflıyorum.', 1),
(156, 'Bir şeyler yapıp sonra ne yaptığımı hatırlayamadığım zamanlar oldu.', 1),
(157, 'Çoğu kez sebepsiz yere cezalandırıldım.', 1),
(158, 'Çabuk ağlarım.', 1),
(159, 'Okuduğumu eskisi kadar iyi anlayamıyorum.', 1),
(160, 'Hayatımda hiçbir zaman kendimi şimdiki kadar iyi hissetmedim.', 5),
(161, 'Bazen başımda bir sızı hissederim.', 'Sağlık'),
(162, 'Birisinin bana kurnazca oyun etmesine çok içerlerim.', 1),
(163, 'Çabucak yorulmam.', 1),
(164, 'Üzerinde çalıştığım konularda okumayı ve incelemelerde bulunmayı severim.', 1),
(165, 'Önemli kimseleri tanımayı severim, çünkü böylece kendimi de önemli bir kimse gibi görürüm.', 1),
(166, 'Yüksek bir yerden aşağıya bakmaya korkarım.', 5),
(167, 'Ailemden herhangi birinin mahkemelik olması beni rahatsız etmez.', 2),
(168, 'Zihnimde bir gariplik var.', 1),
(169, 'Parayı ellemekten korkmam.', 5),
(170, 'Başkalarının hakkımda ne düşündükleri beni rahatsız etmez.', 1),
(171, 'Bir eğlencede başkaları yapsalar bile, ben taşkınlık yapmaktan rahatsız olurum.', 6),
(172, 'Çoğu kez utangaçlığımı örtbas etmek ihtiyacını duyarım.', 1),
(173, 'Okulu severdim.', 1),
(174, 'Hiç bayılma nöbeti geçirmedim.', 'Sağlık'),
(175, 'Pek az başım döner ya da hiç dönmez.', 'Sağlık'),
(176, 'Yılandan büyük bir korkum yoktur.', 5),
(177, 'Annem iyi bir kadındır.', 2),
(178, 'Hafızam genellikle iyidir.', 1),
(179, 'Cinsel konularda sıkıntım vardır.', 4),
(180, 'Yeni tanıştığım kimselerle konuşma konusu bulmada güçlük çekerim.', 6),
(181, 'Canım sıkılınca heyecan yaratmayı severim.', 1),
(182, 'Aklımı oynatmaktan korkuyorum.', 5),
(183, 'Dilencilere para vermeyi doğru bulmam.', 1),
(184, 'Sık sık nereden geldiğini bilmediğim sesler duyarım.', 1),
(185, 'Herkes kadar iyi işitirim.', 'Sağlık'),
(186, 'Bir şeyler yapmaya girişince ellerimin çok defa titrediğini fark ederim.', 'Sağlık'),
(187, 'Ellerimde beceriksizlik ya da sakarlık yok.', 'Sağlık'),
(188, 'Gözlerim yorulmadan uzun süre okuyabilirim.', 'Sağlık'),
(189, 'Çoğu zaman bütün vücudumda bir halsizlik duyarım.', 'Sağlık'),
(190, 'Başım pek az ağrır.', 'Sağlık'),
(191, 'Bazen utanınca çok terlerim.', 'Sağlık'),
(192, 'Yürürken dengemi hemen hemen hiç kaybetmem.', 'Sağlık'),
(193, 'Saman nezlesi ya da astım nöbetlerim yoktur.', 'Sağlık'),
(194, 'Hareketlerimi ve konuşmamı kontrol edemediğim fakat etrafımda olup bitenden haberdar olduğum nöbetler geçirdiğim oldu.', 1),
(195, 'Tanıdığım herkesi sevmem.', 1),
(196, 'Hiç görmediğim yerlere gitmekten hoşlanırım.', 1),
(197, 'Biri beni soymaya (her şeyimi almaya) çalışıyor.', 1),
(198, 'Çok az hayal kurarım.', 1),
(199, 'Çocuklara cinsiyetle ilgili temel gerçekler öğretilmelidir.', 4),
(200, 'Fikir ve düşüncelerimi çalmak isteyen biri var.', 1),
(201, 'Keşke bu kadar utangaç olmasam.', 5),
(202, 'Kendimi cezayı hak etmiş suçlu bir insan olarak görüyorum.', 1),
(203, 'Gazeteci olmak isterdim.', 1),
(204, 'Gazeteci olsaydım daha çok tiyatro haberleri yazmaktan hoşlanırdım.', 1),
(205, 'Bazen çalmaktan ya da dükkanlardan eşya aşırmaktan kendimi alamam.', 1),
(206, 'Birçok kimseden daha çok dindarımdır.', 1),
(207, 'Çeşitli oyun ve eğlencelerden hoşlanırım.', 1),
(208, 'Flört etmeyi severim.', 1),
(209, 'Günahlarımın affedilmeyeceğine inanıyorum.', 1),
(210, 'Her şeyin tadı aynı geliyor.', 'Sağlık'),
(211, 'Gündüzleri uyuyabilirim fakat geceleri uyuyamam.', 'Sağlık'),
(212, 'Evdekiler bana çocuk muamelesi yapıyor.', 2),
(213, 'Yürürken kaldırımdaki yarıklara basmamaya dikkat ederim.', 1),
(214, 'Cildimde üzülmeye değer kabarıklık ya da sivilce yok.', 'Sağlık'),
(215, 'Çok içki kullandım.', 1),
(216, 'Başka ailelere göre bizim evde sevgi ve arkadaşlık pek azdır.', 2),
(217, 'Sık sık kendime bir şeyleri dert edinirim.', 5),
(218, 'Hayvanların eziyet çektiğini görmek beni üzmez.', 1),
(219, 'İnşaat müteahhitliğinden hoşlanacağımı sanıyorum.', 1),
(220, 'Annemi çok severim.', 2),
(221, 'Bilimden hoşlanırım.', 1),
(222, 'Karşılığını veremeyeceğim durumlarda bile arkadaşlarımdan yardım istemekte güçlük çekmem.', 6),
(223, 'Avlanmayı çok severim.', 1),
(224, 'Annem babam hep beraber olduğum kimselerden çok defa hoşlanmıyorlar.', 2),
(225, 'Bazen biraz dedikodu yaptığım olur.', 1),
(226, 'Ailemdeki bazı kişilerde canımı çok sıkan alışkanlıklar var.', 2),
(227, 'Uykuda gezdiğimi söylerler.', 1),
(228, 'Bazen alışılmamış bir kolaylıkla karar verebileceğimi hissediyorum.', 1),
(229, 'Çeşitli kulüp ve derneklere üye olmayı isterim.', 6),
(230, 'Kalbimin hızlı çarptığını hemen hemen hiç hissetmem ve çok seyrek nefesim tıkanır.', 'Sağlık'),
(231, 'Cinsiyet hakkında konuşmayı severim.', 4),
(232, 'Bazen üzerime çok fazla iş alırım.', 1),
(233, 'Pek çok insan karşı çıksa da kendi fikrimi sonuna kadar savunurum.', 6),
(234, 'Çabuk kızar ve çabuk unuturum.', 1),
(235, 'Aile kurallarından oldukça bağımsız ve özgürüm.', 2),
(236, 'Sıklıkla kara kara düşünürüm.', 5),
(237, 'Akrabalarımın hemen hepsi bana karşı anlayış gösterir.', 2),
(238, 'Zaman zaman yerimde duramayacak kadar huzursuzluk duyduğum devreler olur.', 5),
(239, 'Aşkta hayal kırıklığına uğradım.', 4),
(240, 'Görünüşüme hiç aldırmam.', 1),
(241, 'Kendi içimde tutup başkalarına söylenemeyen şeyler hakkında sık sık rüya görürüm.', 1),
(242, 'Birçoklarından daha sinirli sayılmam.', 1),
(243, 'Hemen hemen hiçbir ağrı ve sızım yok.', 'Sağlık'),
(244, 'Davranışlarım başkalarınca yanlış anlaşılmaya elverişlidir.', 1),
(245, 'Ailem beni olduğumdan daha hatalı bulur.', 2),
(246, 'Boynumda sık sık kırmızı lekeler olur.', 'Sağlık'),
(247, 'Kimseden sevgi görmüyorum.', 1),
(248, 'Bazen ortada hiçbir neden yokken hatta işler kötüye gittiği zaman bile kendimi fazlasıyla mutlu hissederim.', 5),
(249, 'Öbür dünyada şeytan ve cehennem olduğuna inanırım.', 1),
(250, 'Hayatta önüne her geleni kapmağa çalışan insanları suçlamam.', 1),
(251, 'Kendimi kaybedip yaptığım işi aksattığım ve etrafımda olup bitenlerin farkında olmadığım zamanlar oldu.', 1),
(252, 'Hiç kimse başkasının derdine aldırış etmiyor.', 1),
(253, 'Hatalı davranışlarını görsem bile insanlara arkadaşça davranabilirim.', 6),
(254, 'Birbiriyle şakalaşan kimseler arasında olmayı severim.', 6),
(255, 'Seçimlerde bazen oyumu pek az tanıdığım kimselere veririm.', 1),
(256, 'Gazetelerin ilgi çeken tek yeri resimli mizah sayfasıdır.', 1),
(257, 'Yaptığım işlerde genel olarak başarı elde edeceğime inanırım.', 1),
(258, 'Allah’ın varlığına inanırım.', 1),
(259, 'İşe başlamada güçlük çekerim.', 1),
(260, 'Okulda iken ağır öğrenenlerden biri idim.', 1),
(261, 'Ressam olsaydım çiçek resimleri yapardım.', 1),
(262, 'Daha güzel olmamam beni rahatsız etmez.', 1),
(263, 'Soğuk günlerde bile kolayca terlerim.', 'Sağlık'),
(264, 'Kendime tam anlamıyla güvenim vardır.', 5),
(265, 'Hiç kimseye güvenmemek en doğrusudur.', 1),
(266, 'Haftada bir ya da daha sık, çok heyecanlanırım.', 5),
(267, 'Topluluk içinde olduğumda üzerinde konuşacak uygun konular bulmakta güçlük çekerim.', 6),
(268, 'Karamsar olduğum zaman heyecanlı bir olay hemen beni bu durumdan çıkarır.', 5),
(269, 'Bazen zevk için başkalarını kendimden korkuturum.', 1),
(270, 'Evden çıkarken kapının kilitli ve pencerenin kapalı olup olmadığı aklıma takılmaz.', 1),
(271, 'Başkalarının saflığını kendi çıkarlarına kullanan kimseleri ayıplamam.', 1),
(272, 'Bazen kendimi enerji dolu hissederim.', 5),
(273, 'Derimin bazı yerlerinde uyuşukluk hissederim.', 'Sağlık'),
(274, 'Görme gücüm eskisi kadar kuvvetlidir.', 'Sağlık'),
(275, 'Birisi zihnimi kontrol ediyor.', 1),
(276, 'Çocukları severim.', 1),
(277, 'Bazen bir madrabazın (Hilecinin) kurnazlığı beni o kadar eğlendirir ki yakayı ele vermemesini dilerim.', 1),
(278, 'Çok defa tanımadığım kimselerin bana eleştirici bir gözle baktıklarını hissederim.', 6),
(279, 'Her gün gereğinden fazla su içerim.', 'Sağlık'),
(280, 'Birçok kimseler kendilerine yararı dokunacağı için arkadaş edinirler.', 1),
(281, 'Kulaklarım çok az çınlar ya da uğuldar.', 'Sağlık'),
(282, 'Genellikle sevdiğim aile üyelerine karşı bazen nefret duyarım.', 2),
(283, 'Gazete muhabiri olsaydım en çok spor haberleri yazmayı isterdim.', 1),
(284, 'Hakkımda çok konuşulduğundan eminim.', 1),
(285, 'Arasıra açık saçık bir fıkraya güldüğüm olur.', 1),
(286, 'En çok yalnız olduğum zaman mutlu olurum.', 5),
(287, 'Arkadaşlarıma kıyasla beni korkutan şeyler çok azdır.', 5),
(288, 'Tekrarlanan mide bulantısı ve kusmalar bana sıkıntı verir.', 'Sağlık'),
(289, 'Bir suçlu avukatın becerikliliği sayesinde cezadan kurtulunca kanunlara karşı daima nefret duyarım.', 1),
(290, 'Çok gergin bir hava içinde çalışıyorum.', 5),
(291, 'Hayatımda bir ya da birkaç kere birisinin beni hipnotize ederek bana bir şeyler yaptığını hissettim.', 1),
(292, 'Başkaları benimle konuşuncaya kadar ben onlarla konuşmağa başlamam.', 6),
(293, 'Birisi zihnimi etkilemeye çalışıyor.', 1),
(294, 'Kanunla hiç başım derde girmedi.', 1),
(295, 'Masal okumayı severim.', 1),
(296, 'Hiçbir neden yokken kendimi son derece neşeli hissettiğim zamanlar olur.', 5),
(297, 'Cinsiyetle ilgili düşünceler beni rahatsız eder.', 4),
(298, 'Birkaç kişinin birlikte başları derde girince en iyisi yakalarını kurtarmak için aynı hikayeyi uydurmak ve bundan caymamaktır.', 1),
(299, 'Duygularımın birçok kimselerden yoğun olduğunu düşünürüm.', 5),
(300, 'Hayatımda hiçbir zaman bebekle oynamaktan hoşlanmadım.', 1),
(301, 'Çoğu zaman hayat benim için bir yüktür.', 5),
(302, 'Cinsel davranışlarımdan dolayı hiçbir zaman başım derde girmedi.', 4),
(303, 'Bazı konularda o kadar alınganım ki onlar hakkında konuşmam bile.', 5),
(304, 'Okulda sınıf karşısında konuşmak bana çok güç gelirdi.', 6),
(305, 'Başkalarıyla beraber olduğum zaman bile kendimi yalnız hissederim.', 6),
(306, 'Bana karşı mümkün olan anlayış gösteriliyor.', 1),
(307, 'İyi beceremediğim oyunları oynamaya yanaşmam.', 1),
(308, 'Zaman zaman evi bırakıp gitmeyi çok istemişimdir.', 1),
(309, 'Birçokları kadar çabuk arkadaş edinebildiğimi sanıyorum.', 6),
(310, 'Cinsel hayatım doyurucudur.', 4),
(311, 'Gençlik yıllarımda bir devre ufak tefek şeyler çaldım.', 1),
(312, 'İnsanların arasında olmaktan hiç hoşlanmam.', 6),
(313, 'Değerli eşyasını tedbirsizce ortada bırakıp çalınmasına neden olan kimse bunu çalan kadar hatalıdır.', 1),
(314, 'Arasıra söylenemeyecek kadar kötü şeyler düşünürüm.', 1),
(315, 'Hayatın hep kötü tarafları bana nasip olmuştur.', 1),
(316, 'Hemen hemen herkesin başını derde sokmamak için yalan söyleyebileceğine inanırım.', 1),
(317, 'Birçok kimselerden daha hassasım.', 5),
(318, 'Günlük hayatım beni ilgilendiren şeylerle dolu.', 1),
(319, 'İnsanların çoğu başkalarına yardım etmek için zahmete girmekten hoşlanmazlar.', 1),
(320, 'Rüyalarımın çoğu cinsel konularla ilgilidir.', 4),
(321, 'Kolaylıkla mahcup olurum.', 5),
(322, 'Para ve işi kendime dert ederim.', 5),
(323, 'Başımdan çok tuhaf ve acayip olaylar geçmiştir.', 1),
(324, 'Hiç kimseye aşık olmadım.', 4),
(325, 'Ailemin yaptığı bazı şeyler beni korkutmuştur.', 2),
(326, 'Bazen kontrol edemediğim gülme ve ağlama nöbetlerine tutulurum.', 1),
(327, 'Annem ya da babam çok defa beni makul bulmadığım emirlere bile itaat ettirdiler.', 2),
(328, 'Zihnimi bir konu ya da iş üzerinde toplamakta güçlük çekerim.', 1),
(329, 'Hemen hemen hiç rüya görmedim.', 1),
(330, 'Hiç felç geçirmedim ya da kaslarımda olağanüstü bir halsizlik duymadım.', 'Sağlık'),
(331, 'Eğer insanlar sırf düşmanlık olsun diye beni engellemeselerdi daha başarılı olurdum.', 1),
(332, 'Bazen nezle olmadığım halde sesim çıkmaz ya da değişir.', 'Sağlık'),
(333, 'Beni hiç kimse anlamıyor.', 1),
(334, 'Bazen tuhaf kokular duyarım.', 1),
(335, 'Zihnimi bir konu üzerinde toplayamam.', 1),
(336, 'İnsanlara karşı sabrım çabuk tükenir.', 1),
(337, 'Çoğunlukla bir takım şeyler ve kimseler için meraklanıp huzursuzlanırım.', 5),
(338, 'Hayatımın çoğu kimselerinkinden daha fazla tasa ve kaygı içinde geçtiğine eminim.', 5),
(339, 'Çoğu zaman ölmüş olmayı isterdim.', 5),
(340, 'Bazen o kadar heyecanlanırım ki uykuya dalmam güçleşir.', 'Sağlık'),
(341, 'Bazen beni rahatsız edecek kadar iyi işitirim.', 'Sağlık'),
(342, 'Bana söylenenleri hemen unuturum.', 1),
(343, 'Önemsiz ufak şeylerde bile karar verip işe girişmeden önce durur ve düşünürüm.', 1),
(344, 'Gördüğüm kimse ile karşılaşmamak için sıklıkla yolumu değiştiririm.', 6),
(345, 'Sıklıkla olup bitenler bana gerçek değilmiş gibi gelir.', 1),
(346, 'Reklamlardaki ampuller gibi önemsiz şeyleri sayma alışkanlığım vardır.', 1),
(347, 'Bana gerçekten kötülük yapmak isteyen hiçbir düşmanım yoktur.', 1),
(348, 'Bana umduğumdan fazla dostluk gösteren insanlara karşı tetikte bulunmağa çalışırım.', 6),
(349, 'Acayip ve tuhaf düşüncelerim vardır.', 1),
(350, 'Yalnızken garip şeyler duyarım.', 1),
(351, 'Küçük bir seyahat için bile evden ayrılırken telaşlanır ve kaygılanırım.', 5),
(352, 'Beni incitmeyeceğini bildiğim şeylerden ya da insanlardan bile korktuğum oldu.', 5),
(353, 'Başkalarının daha önce toplanıp konuştuğu odaya girmekten çekinmem.', 6),
(354, 'Bıçak gibi çok keskin ve sivri şeyler kullanmaktan korkarım.', 5),
(355, 'Sevdiğim kimseleri bazen incitmekten hoşlanırım.', 1),
(356, 'Dikkatimi bir konu üzerinde toplamada birçok kişiden daha fazla güçlük çekerim.', 1),
(357, 'Yeteneğimi küçümsediğim için birçok defalar başladığım işi yarıda bıraktım.', 5),
(358, 'Kötü ve çok defa korkunç kelimeler zihnimi kurcalar ve bunlardan kendimi kurtaramam.', 1),
(359, 'Bazen önemsiz düşünceler aklımdan geçer ve beni günlerce rahatsız eder.', 1),
(360, 'Hemen hemen her gün beni korkutan bir şey olur.', 5),
(361, 'Her şeyi kötüye yorma eğilimindeyim.', 1),
(362, 'Birçok kimselerden çok daha hassasım.', 5),
(363, 'Bazen sevdiğim kimselerin beni incitmesinden hoşlandığım oldu.', 1),
(364, 'Hakkımda onur kırıcı ve kötü sözler söylüyorlar.', 1),
(365, 'Kapalı yerlerde huzursuzluk duyarım.', 5),
(366, 'İnsanlar arasında bile olsam çok defa kendimi yalnız hissederim.', 6),
(367, 'Yangından korkmam.', 5),
(368, 'Sonradan pişman olacağım şeyler yapmak ya da söylemek korkusuyla bazen bir kimseden uzak durduğum oldu.', 5),
(369, 'Kararsızlığım yüzünden yapılması gerekli birçok işi yapamamışımdır.', 1),
(370, 'Çalışırken acele etmek zorunda olmaktan nefret ederim.', 1),
(371, 'Aşırı derecede kendini dinleyen bir insan değilim.', 1),
(372, 'Elimdeki işi en iyi şekilde yapmayı isterim.', 1),
(373, 'Yalnızca bir tek doğru din olduğundan eminim.', 1),
(374, 'Ara sıra zihnim her zamankinden daha ağır işler.', 1),
(375, 'Çok mutlu olduğum ve iyi çalıştığım zamanlarda neşesiz veya dertli bir insanla karşılaşmak keyfimi tamamen kaçırır.', 6),
(376, 'Polisler genellikle dürüsttür.', 1),
(377, 'Toplantılarda kalabalığa karışmaktan çok yalnız başıma oturur ya da bir tek kişiyle ahbaplık ederim.', 6),
(378, 'Kadınları sigara içerken görmekten hoşlanmam.', 1),
(379, 'Çok nadiren karamsarlığa kapılırım.', 5),
(380, 'Ne yapsam zevk alamıyorum.', 5),
(381, 'Kolay öfkelenen biri olduğumu söylerler.', 1),
(382, 'Yapmak istediğim şeylere karar verirken, başkalarının ne düşüneceğini dikkate almam.', 1),
(383, 'İnsanlar çoğu zaman beni hayal kırıklığına uğratırlar.', 1),
(384, 'Kendimle ilgili her şeyi anlatabileceğim hiç kimse yok.', 6),
(385, 'Şimşek çakması da korkularımdan biridir.', 5),
(386, 'Çok tertipli ve titizim.', 1),
(387, 'Ailem her davranışıma fazla karışıyor.', 2),
(388, 'Karanlıkta yalnız kalmaktan korkarım.', 5),
(389, 'Tasarlamış olduğum planlar çok defa o kadar güçlükle dolu göründü ki bunlardan vazgeçmek zorunda kaldım.', 1),
(390, 'Birinin hatasını önleme gayretimin yanlış anlaşılmasına çok üzülürüm.', 1),
(391, 'Dansa gitmeyi severim.', 1),
(392, 'Fırtınadan çok korkarım.', 5),
(393, 'Yük çekmeyen atlar dövülmeli ya da kamçılanmalıdır.', 1),
(394, 'Başkalarına sık sık akıl danışırım.', 6),
(395, 'Gelecek, bir insanın ciddi planlar yapamayacağı kadar belirsizdir.', 1),
(396, 'İşler yolunda gittiği zaman bile çoğu kez her şeye karşı bir aldırmazlık içinde olduğumu hissederim.', 5),
(397, 'Bazen güçlükler öylesine üst üste gelir ki onlarla baş edemeyecekmişim gibi hissederim.', 5),
(398, 'Çoğu kez “Keşke tekrar çocuk olsaydım” diye düşünürüm.', 1),
(399, 'Kolay kolay kızmam.', 1),
(400, 'Eğer bana fırsat verilse dünya için çok yararlı işler yapabilirim.', 1),
(401, 'Sudan hiç korkmam.', 5),
(402, 'Ne yapacağıma karar vermeden önce uzun uzun düşünürüm.', 1),
(403, 'Birçok şeyin olup bittiği böyle bir devirde yaşamak hoş bir şey.', 1),
(404, 'Hatalarını düzelterek kendilerine yardım etmeye çalıştığım insanlar amacımı çoğu kez yanlış anlarlar.', 1),
(405, 'Yutkunmakta güçlük çekmem.', 'Sağlık'),
(406, 'Uzman dendiği halde benden pek fazla bilgili olmayan insanlarla sıklıkla karşılaşırım.', 1),
(407, 'Genel olarak sakinim ve kolay sinirlenmem.', 1),
(408, 'Bazı konular hakkında hislerimi o kadar gizleyebilirim ki insanlar bilmeden beni incitebilirler.', 6),
(409, 'Elimde olmadan çok ufak bir şeyden münakaşa çıkarıp karşımdakini kırıyorum.', 1),
(410, 'Madrabazı (hilekarı) kendi silahı ile alt etmekten hoşlanırım.', 1),
(411, 'İyi tanıdığım bir kimsenin başarısını duyduğum zaman adeta kendimi başarısızlığa uğramış hissederim.', 5),
(412, 'Hastalandığım zaman doktora gitmekten korkmam.', 'Sağlık'),
(413, 'Günahlarım için ne kadar ağır ceza görsem iyidir.', 1),
(414, 'Hayal kırıklıklarını o kadar ciddiye alırım ki bunları zihnimden söküp atamam.', 5),
(415, 'Fırsat verilse iyi bir önder olurum.', 1),
(416, 'Yakınlarımın sağlığından çok endişe ederim.', 5),
(417, 'Sırada beklerken biri önüme geçmeye kalkışırsa ona çıkışırım.', 1),
(418, 'Bazen hiçbir işe yaramadığımı düşünürüm.', 5),
(419, 'Küçükken okuldan sık sık kaçardım.', 1),
(420, 'Başımdan dinle ilgili olağanüstü yaşantılar geçti.', 1),
(421, 'Ailemde çok sinirli insanlar var.', 2),
(422, 'Ailemde bazı kişilerin yapmış olduğu işler beni utandırmıştır.', 2),
(423, 'Balık tutmayı çok severim.', 1),
(424, 'Hemen hemen her zaman açlık duyarım.', 'Sağlık'),
(425, 'Sık sık rüya görürüm.', 1),
(426, 'Kaba ya da can sıkıcı insanlara karşı bazen sert davrandığım olur.', 6),
(427, 'Açık saçık hikayelerden utanıp rahatsız olurum.', 1),
(428, 'Gazetelerin baş yazılarını okumaktan hoşlanırım.', 1),
(429, 'Ciddi konular üzerinde verilen konferansları dinlemekten hoşlanırım.', 1),
(430, 'Karşı cinsten olanları çekici bulurum.', 4),
(431, 'Başa gelebilecek talihsizlikler beni oldukça telaşlandırır.', 5),
(432, 'Kuvvetli siyasi fikirlerim vardır.', 1),
(433, 'Bir zamanlar hayali arkadaşlarım vardı.', 1),
(434, 'Otomobil yarışçısı olmayı isterdim.', 1),
(435, 'Genel olarak kadınlarla çalışmayı tercih ederim.', 1),
(436, 'İnsanlar genel olarak başkalarının haklarına saygı göstermekten çok kendi haklarına saygı gösterilmesini isterler.', 1),
(437, 'Kanuna aykırı davranmadan kanunun bir gediğinden yararlanmakta zarar yoktur.', 1),
(438, 'Bazı insanlardan o kadar nefret ederim ki ettiklerini bulunca içimden oh derim.', 1),
(439, 'Beklemek zorunda kalmak beni sinirlendirir.', 1),
(440, 'Başkalarına anlatmak için hoş fıkraları hatırımda tutmaya çalışırım.', 1),
(441, 'Uzun boylu kadınlardan hoşlanırım.', 1),
(442, 'Üzüntü yüzünden uyuyamadığım zamanlar oldu.', 5),
(443, 'Başkalarının gereği gibi yapamadığımı sandığı şeyleri yapmaktan vazgeçtiğim oldu.', 1),
(444, 'Başkalarının cahilce inançlarını düzeltmeye çalışmam.', 1),
(445, 'Küçükken heyecan veren şeyler yapmaktan hoşlanırdım.', 1),
(446, 'Az parayla oynanan kumardan hoşlanırım.', 1),
(447, 'Mastürbasyonda kendi cinsimle ilgili hayal beni tahrik eder.', 4),
(448, 'Sokakta, otobüs ve dükkanlarda bana bakan insanlardan rahatsız olurum.', 6),
(449, 'İnsanlarla bir arada olmayı sağladığı için toplantı ve davetleri severim.', 6),
(450, 'Kalabalığın verdiği coşkudan hoşlanırım.', 6),
(451, 'Neşeli arkadaşlar arasına karışınca üzüntülerimi unuturum.', 5),
(452, 'Arkadaş edinemiyorum.', 6),
(453, 'Küçükken mahalledeki arkadaş ya da akran gruplarına katılmaktan hoşlanmazdım.', 6),
(454, 'Orman ya da dağdaki bir kulübede tek başıma yaşamaktan mutlu olabilirim.', 6),
(455, 'İçinde bulunduğum grubun dedikodularına ve konuşmalarına sıklıkla konu olmam.', 6),
(456, 'İnsan makul bulmadığı kanunlara aykırı hareketlerinden ötürü cezalandırılmamalıdır.', 1),
(457, 'Bence insan hiçbir zaman alkollü bir içkiyi ağzına almamalıdır.', 1),
(458, 'Çocukken benimle en fazla ilgilenen erkek (baba, üvey baba vb.) bana karşı çok sert davrandı.', 2),
(459, 'Çaba göstermekle yenemeyeceğimi bildiğim bazı kötü alışkanlıklarım var.', 1),
(460, 'Az içki kullandım ya da hiç kullanmadım.', 1),
(461, 'Kısa bir zaman için bile olsa başladığım işi bir kenara bırakmak bana güç gelir.', 1),
(462, 'Küçük abdestimi yapmada ya da tutmada güçlük çekmem.', 'Sağlık'),
(463, 'Seksek oyunu oynamaktan hoşlanırdım.', 1),
(464, 'Hiç hayal görmedim.', 1),
(465, 'Birkaç kez hayatım boyunca yaptığım işte hevesimi yitirdiğim olmuştur.', 1),
(466, 'Doktor önerisi dışında hiçbir ilaç ya da uyku hapı kullanmadım.', 'Sağlık'),
(467, 'Çok defa (otomobil, plaka numarası gibi) hiç önemli olmayan numaraları ezberlerim.', 1),
(468, 'Sıklıkla sinirli ve asık suratlı olurum.', 5),
(469, 'Onlardan önce düşündüğüm için başkaları benim fikirlerimi kıskanıyorlar.', 1),
(470, 'Cinsiyetle ilgili şeylerden nefret ederim.', 4),
(471, 'Okulda hal ve gidişten kırık not alırdım.', 1),
(472, 'Yangın karşısında büyülenmiş gibi olurum.', 1),
(473, 'Mümkün olduğu kadar kalabalıktan uzak kalmaya çalışırım.', 6),
(474, 'Başkalarından daha sık küçük abdeste çıkmam.', 'Sağlık'),
(475, 'Sıkıştırıldığım zaman gerçeğin ancak bana zarar vermeyeceği kısmını söylerim.', 1),
(476, 'Tanrı bana özel bir görev vermiştir.', 1),
(477, 'Arkadaşlarımla birlikte işlediğim bir suçtan eşit şekilde suçlu olduğum zaman onları ele vermektense bütün suçu üzerime almayı tercih ederim.', 1),
(478, 'Çok değişik bir aile ortamından gelmiş olmayı isterdim.', 2),
(479, 'Yabancılarla tanışmaktan kaçınmam.', 6),
(480, 'Karanlıktan çok defa korkarım.', 5),
(481, 'Bir şeyden kurtulmak için hasta numarası yaptığım olmuştur.', 1),
(482, 'Trende, otobüste vb. rastladığım kimselerle çok defa konuşurum.', 6),
(483, 'Peygamberimiz göğe çıkma gibi mucizeler göstermiştir.', 1),
(484, 'Homoseksüelliği çok iğrenç buluyorum.', 4),
(485, 'Bir erkek bir kadınla beraber olunca genel olarak onun cinsiyetiyle ilgili şeyler düşünür.', 4),
(486, 'İdrarımda hiçbir zaman kan görmedim.', 'Sağlık'),
(487, 'Uğraştığım iş yolunda gitmeyince hemen vazgeçerim.', 1),
(488, 'Sık sık dua ederim.', 1),
(489, 'Yaşamı yalnızca üzüntülü, sıkıntılı tarafları ile benimseyen insanlara sempati duyarım.', 1),
(490, 'Haftada birkaç kere Kur’an okurum.', 1),
(491, 'Sadece bir tek dinin doğruluğuna inananlara tahammül edemem.', 1),
(492, 'Zelzele düşüncesi beni çok korkutur.', 5),
(493, 'Tam dikkat isteyen işleri, beni dikkatsizliğe sürükleyen işlere tercih ederim.', 1),
(494, 'Kapalı ve küçük yerlerde bulunmaktan çok rahatsız olurum.', 5),
(495, 'Kusurlarını düzeltmeye çalıştığım insanlarla genel olarak gayet açık konuşurum.', 6),
(496, 'Eşyayı hiçbir zaman çift görmem (Yani tek olan şeyleri çift görmem.)', 'Sağlık'),
(497, 'Macera hikayelerinden hoşlanırım.', 1),
(498, 'Açık sözlü olmak her zaman iyidir.', 1),
(499, 'Gerçekten önemsiz olan bir şey üzerinde bazen sebepsiz olarak haddinden fazla üzüldüğüm olur.', 1),
(500, 'Bana parlak gelen bir fikre hemen kapılır giderim.', 1),
(501, 'Başkalarından yardım beklemektense genel olarak bir işi kendi başıma yapmayı tercih ederim.', 6),
(502, 'Herhangi bir olay hakkındaki görüşümü başkalarına açıkça belirtmekten hoşlanırım.', 6),
(503, 'Başkalarının hareketlerini çok beğenip beğenmediğimi pek belli etmem.', 1),
(504, 'Değersiz gördüğüm ya da acıdığım kimseye bu duygularımı belli etmem.', 6),
(505, 'Zaman zaman kendimi öyle güçlü ve enerjik hissederim ki böyle zamanlarda günlerce uykuya ihtiyaç duymadığım olur.', 1),
(506, 'Sinirleri çok gergin bir insanım.', 5),
(507, 'İşler iyi gidince aslan payını kendilerine alan fakat hata yapılınca bunu başkalarının üzerine atan insanlarla karşılaştım.', 1),
(508, 'Koku alma duyum herkes kadar iyidir.', 'Sağlık'),
(509, 'Bazen çekingenliğim yüzünden hakkımı arayamam.', 6),
(510, 'Pislik ve kir beni ürkütüp iğrendirir.', 1),
(511, 'Herkesten gizli tuttuğum bir hayal dünyam var.', 1),
(512, 'Yıkanmaktan hoşlanmam.', 1),
(513, 'Kış mevsimini severim.', 1),
(514, 'Erkek gibi davranan kadınlardan hoşlanırım.', 1),
(515, 'Evimizde daima gerekli ihtiyaç maddeleri bulunurdu (yeteri kadar yiyecek, giyecek vs. gibi).', 1),
(516, 'Ailemde çabuk kızan kimseler var.', 2),
(517, 'Hiçbir şeyi iyi yapamam.', 5),
(518, 'Bazı durumlarda olduğumdan daha fazla üzüntülü görünmeye çalıştığım olmuştur.', 1),
(519, 'Cinsel organlarımda bir bozukluk var.', 4),
(520, 'Genel olarak görüşlerimi kuvvetle savunurum.', 6),
(521, 'Bir grup içinde konuşma yapmam ve çok iyi bildiğim bir konuda fikrimi söylemem istenince kaygılanmam.', 6),
(522, 'Örümcekten korkmam.', 5),
(523, 'Yüzüm hemen hemen hiç kızarmaz.', 'Sağlık'),
(524, 'Kapı tokmaklarından hastalık veya mikrop alacağımdan korkmam.', 5),
(525, 'Bazı hayvanlardan ürkerim.', 5),
(526, 'Gelecek bana ümitsiz görünüyor.', 5),
(527, 'Ailem ve yakın akrabalarım birbirleri ile oldukça iyi geçinirler.', 2),
(528, 'Yüzüm başkalarından daha sık kızarmaz.', 'Sağlık'),
(529, 'Pahalı elbiseler giymeyi isterim.', 1),
(530, 'Sebepsiz yere sık sık içim sıkılıyor ve ağlamak istiyorum.', 5),
(531, 'Bir konu üzerinde karar verdiğimi zannetsem bile başka biri fikrimi kolayca değiştirebilir.', 1),
(532, 'Acıya başkaları kadar ben de dayanabilirim.', 'Sağlık'),
(533, 'Sık sık geğirmekten şikayetim yoktur.', 'Sağlık'),
(534, 'Çoğunlukla başladığım işten en son vazgeçen ben olurum.', 1),
(535, 'Hemen hemen her zaman ağzımda kuruluk olur.', 'Sağlık'),
(536, 'Beni acele ettirenlere kızarım.', 1),
(537, 'Afrika’da arslan avına çıkmak isterdim.', 1),
(538, 'Terzilikten hoşlanabileceğimi sanmıyorum.', 1),
(539, 'Fareden korkmam.', 5),
(540, 'Yüzüme hiç felç inmedi.', 'Sağlık'),
(541, 'Cildime ufak bir şeyin dokunmasından çok huylanırım.', 'Sağlık'),
(542, 'Şimdiye kadar rengi kapkara büyük abdest yapmadım.', 'Sağlık'),
(543, 'Haftada birkaç kez korkunç bir şey olacakmış duygusuna kapılırım.', 5),
(544, 'Çoğu zaman yorgunluk hissederim.', 'Sağlık'),
(545, 'Bazen aynı rüyayı tekrar tekrar görürüm.', 1),
(546, 'Tarih okumaktan hoşlanırım.', 1),
(547, 'Toplantı ve kalabalık eğlencelerden hoşlanırım.', 6),
(548, 'Elimdeyse açık saçık numaraların yapılacağı eğlence yerlerine gitmem.', 1),
(549, 'Karşıma çıkacak güçlüklerden korkar ve kaçarım.', 5),
(550, 'Kapı mandallarını onarmaktan hoşlanırım.', 1),
(551, 'Bazen başkalarının kafamın içindekileri okuduğundan eminim.', 1),
(552, 'Bilimsel yayınları okumaktan hoşlanırım.', 1),
(553, 'Açık yerlerde veya geniş meydanlarda tek başıma kalmaktan korkarım.', 5),
(554, 'Sıkıntım oldukça alkol alırım.', 1),
(555, 'Bazen çıldıracakmış gibi olurum.', 5),
(556, 'Kılık kıyafetime çok dikkat ederim.', 1),
(557, 'Hayatı fazla ciddiye almıyorum.', 1),
(558, 'Birçok kimseler kötü cinsel faaliyetlerinden dolayı suçludurlar.', 4),
(559, 'Gece yarısı çoğunlukla korkuya kapıldığım olur.', 5),
(560, 'Bir şeyi nereye koyduğumu unutmaktan çok şikayetçiyimdir.', 1),
(561, 'Ailem benim için büyük bir dayanaktır.', 2),
(562, 'Çocukken en fazla bağlandığım ve hayran kaldığım kimse bir kadındı.', 1),
(563, 'Macera hikayelerini aşk hikayelerinden daha çok severim.', 1),
(564, 'Yapmak istediğim fakat başkalarının beğenmediği bir işten kolayca vazgeçerim.', 6),
(565, 'Yüksek bir yerde iken içimden atlama isteği gelir.', 5),
(566, 'Sinemalardaki aşk sahnelerini severim.', 4);