server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Statik ön yüz dosyalarınızın sunulması (./frontend dizini buraya bağlanır)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # SPA (Single Page Application) yönlendirme desteği
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # yz Yonlendirmesi
    location /yz/ {
        proxy_pass http://yz_upstream;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /yz;
    }

    # pgAdmin Yönlendirmesi
    location /pgadmin/ {
        proxy_pass http://pgadmin_upstream;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /pgadmin;
    }

    # E2E Test Runner Yönlendirmesi (host üzerinde node server.js ile çalışır)
    location /test-runner/ {
        proxy_pass http://172.23.0.1:3099/;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # PostgREST API Yönlendirmesi
    location /api/ {
        proxy_pass http://postgrest_api_upstream/;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Güvenlik Başlıkları
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}

# --- UPSTREAM SUNUCULARI ---
# docker-compose.yml dosyanızdaki yeni servis isimleri (api ve pgadmin) ile eşleştirildi.

upstream postgrest_api_upstream {
    server api:3000; # 'selma-postgrest' yerine compose servis adı olan 'api' yazıldı
    keepalive 64;
}

upstream pgadmin_upstream {
    server pgadmin:80; # 'selma-pgadmin' yerine compose servis adı olan 'pgadmin' yazıldı
    keepalive 64;
}

upstream yz_upstream {
    server 172.16.1.31:18080; 
    keepalive 64;
}
